### ISSUE TITLE
Is there a way to disable an export option?

### ISSUE THREAD

**Issue by ieglonew01f** [jupyter/nbconvert#1065]
Currently, I'm trying to disable pdf exports and latex exports is there a way to do so? Is there an option to blacklist certain exports?

**Comment by MSeal** [comment]
Well, if latex isn't installed the exports will fail. There's not an ability to remove the export options from the `--to` list afaik.

**Comment by rahulpshah** [comment]
I am trying to disable pdf exporter for nbconvert based so that it does not show as an option when someone uses Jupyterlab. I don't have latex packages on the host machine so it does not make sense to show pdf as an option.
Have a c.NbExporter.blacklist_exporters = [""] in jupyter_server_config.py to specify valid exporters.
