### ISSUE TITLE
Embedded images out of order in pdf

### ISSUE THREAD

**Issue by deprekate** [jupyter/nbconvert#1168]
If plotting was done with a function, embedded images can appear out of order after pdf conversion.

Recreate the bug
1. load matplotlib
2. create a dummy function that plots something and in same cell call that fuction
3. in the next cell call the same function
4. embed an image using markup
5. download as pdf via latex

Screenshot of jupyter notebook:
![Screen Shot 2020-01-13 at 10 23 57 PM](https://user-images.githubusercontent.com/1821312/72319447-0955eb80-3654-11ea-950d-a65762ca8144.png)

Screenshot of exported PDF
![Screen Shot 2020-01-13 at 10 25 30 PM](https://user-images.githubusercontent.com/1821312/72319460-0e1a9f80-3654-11ea-910a-aa423b483ea9.png)

**OSX:**
10.11.6
**Nbconvert version:**
5.4.0

**Comment by MSeal** [comment]
Hmm I am unable to reproduce this in 5.4.0 (though I don't have an OSX setup). You are using a very old version of nbconvert -- have you tried from nbconvert 5.6.1? Also it looks like OSX 10.11 requires an older MacTeX package based on http://tug.org/mactex/faq/3-4.html -- I'd make sure your using the latest version of that library available for your OS, though it's possible this is an issue fixed in the version that requires 10.12.

**Comment by deprekate** [comment]
Ah, I had the newest nbconvert, but my jupyter was old (3.7) and used the nbconvert-5.4.0

I updated jupyter, and now it uses 6.0.0a0.dev0 and my text example is rendering to PDF correctly as well as my original larger notebook
