### ISSUE TITLE
nbconvert doesn't use theme

### ISSUE THREAD

**Issue by beasteers** [jupyter/nbconvert#1216]
Nbconvert doesn't export using JupyterLab custom themes.

- Enable a custom theme
- Run `Export Notebook as HTML`
- Open downloaded file and 😕

After a quick dig thru the master branch, I found where the template chooses the theme styling (I think) and it's hardcoded to only work with the default light/dark themes.

https://github.com/jupyter/nbconvert/blob/master/share/jupyter/nbconvert/templates/lab/index.html.j2

I don't know how hard it would be to extend this to handle other themes, but I'd imagine that the infrastructure is mostly there seeing as you can render the html fine inside of lab.

**Nbconvert version:** 5.6.1

Update: actually it doesn't work for (builtin) dark mode either. It just looks like old jupyter notebook styling. Hmm.

**Comment by SylvainCorlay** [comment]
@beasteers we have not tagged a release supporting JupyterLab themes.

With nbconvert 6.0, it will be possible to produce a JupyterLab-style HTML export, with support for dark and light theme.

We have no specific plan for custom themes yet.

**Comment by redNixon** [comment]
@SylvainCorlay 
The [docs](https://nbconvert.readthedocs.io/en/latest/config_options.html#exporter-options) seem to have suggested that it is already possible to configure a JupyterLab CSS theme by this commit(I think): https://github.com/jupyter/nbconvert/commit/f4c7daefe0e24055a92f185d6fd803abf909db2f 

>HTMLExporter.theme : Unicode
>Default: 'light'
>
>Template specific theme(e.g. the JupyterLab CSS theme for the lab template)

Or at least that is what I understood that config option's help text to mean when I read it before spending time trying to debug why it was not applying.  Would you say that this is a documentation bug since switching to "dark" is not supported yet or I am completely off the mark and this is documenting something complete different than what this issue is requesting?

**Comment by SylvainCorlay** [comment]
@redNixon this link to "latest" documentation reflects the state kf the master branch but there is no release with that feature yet.

**Comment by martinRenou** [comment]
First attempt to fixing this issue: https://github.com/jupyter/nbconvert/pull/1703
