### ISSUE TITLE
how export ipynb as html_with_toc?

### ISSUE THREAD

**Issue by slsongge** [jupyter/nbconvert#1228]
Hi，I want to export ".ipynb" as a html that with table with contents. I try to use `jupyter nbconvert --to html_toc FILE.ipynb` do it, but fail.

**Comment by slsongge** [comment]
The file of “zip” is  an example.
[test_02.zip](https://github.com/jupyter/nbconvert/files/4426016/test_02.zip)

**Comment by joelostblom** [comment]
You can do this by installing the `toc2` extension, which enables the `html_toc` export formar. I wrote [an answer on SO](https://stackoverflow.com/a/59286150/2166823) that goes through this in detail, scroll down to the heading "In an exported HTML file".

**Comment by slsongge** [comment]
@joelostblom 
Thank you, I fulfilled my needs according to your method.

**Comment by slsongge** [comment]
@ joelosblom
When I sent this file(html_with_toc) to others, I found that the other party did not display the toc.
Do you know how to display the directory in non-local？
Thanks！

**Comment by JiaxiangBU** [comment]
> [Here is an example](https://joelostblom.github.io/teaching-notebooks/notebooks/eda-pointers.html) I have made.

Hi, @joelostblom I try this one, but the TOC doesn't work.
Here is a screenshot to show the output.

![image](https://user-images.githubusercontent.com/15884785/78465390-9a0a0800-7727-11ea-8cc1-1968d994b1f2.png)

**Comment by slsongge** [comment]
@joelostblom JiaxiangBU is my friend, I shared [this issue](https://github.com/jupyter/nbconvert/issues/1228#issuecomment-609084243) to him.
I am able to see ToC in my browser, but he can't. I think the reason I can see is the configuration of my local jupyter.
![image](https://user-images.githubusercontent.com/36298417/78465594-58c72780-772a-11ea-84ac-e7c3104da296.png)

**Comment by joelostblom** [comment]
@slsongge The output is just an HTML page, so nothing about your local jupyter configuration matters, only your browser.

@JiaxiangBU That is strange, I would try disabling all browser addons (running incognito if in chrome) and try a different browser. If you right click the page and inspect the HTML source, you will see that the ToC elements are there, so it is just a matter of your browser rendering them properly.

**Comment by slsongge** [comment]
@joelostblom 
I asked a friend who learned front-end, he said it was because part of the content in the webpage source code could not be opened.
![image](https://user-images.githubusercontent.com/36298417/78466377-faeb0d80-7732-11ea-9d11-b2d021c228d5.png)

**Comment by JiaxiangBU** [comment]
> @JiaxiangBU That is strange, I would try disabling all browser addons (running incognito if in chrome) and try a different browser. If you right-click the page and inspect the HTML source, you will see that the ToC elements are there, so it is just a matter of your browser rendering them properly.

@joelostblom My default browser is Chrome, so I use IE to access this HTML file.
But the output is the same, here is a screenshot to show it.

![image](https://user-images.githubusercontent.com/15884785/78466588-63d38500-7735-11ea-9366-a295722e0513.png)

**Comment by joelostblom** [comment]
I thought it could be a problem with not fetching those resources @slsongge, but I expected it to fall back to rendering a simple version of the toc rather than failing completely. The reason for that is when I download the HTML file (right click the page and save as), deleted the directory with the same name as the HTML file, and turn off my wifi, I can still see the toc, just a barebones version of it. Try that and let me know if you see something like this:


![image](https://user-images.githubusercontent.com/4560057/78467368-dc4c2e80-76c0-11ea-923e-42716b984f51.png)

From left to right:
1. Downloaded version with wifi on
2. Downloaded version with wifi off (notice that some symbols in the toc can't load)
3. Downloaded version after deleting the directory that is downloaded with the same name as the html file (this contains all the css and js). You should at least be able to see the toc like this.

If this doesn't work I am out of ideas unfortunately, and I would ask your question as an html/web question on stackoverflow.

**Comment by JiaxiangBU** [comment]
Hi @joelostblom we @slsongge and I may figure out the problem. Because of the connection or GFW, when we build html, we cannot access some js files. Those result in we cannot preview the html file with TOC.

We make a minimal example, here,

1. Js files, https://github.com/JiaxiangBU/tutoring2/tree/master/jinxiaosong/nb2gitbook/toc_and_pyecharts
1. The GitHub pages address https://jiaxiangbu.github.io/tutoring2/jinxiaosong/nb2gitbook/toc_and_pyecharts/toc_and_pyecharts.html

**Comment by joelostblom** [comment]
Ah, yeah if you're behind a restrictive firewall that might indeed cause issues (I can see the toc of the link you posted in 2. above). But nice that you figured it out! You can go ahead and close this issue then since it is not really related to nbconvert.

**Comment by JiaxiangBU** [comment]
I agree with you, it is not an issue about nbconvert. Thanks for your reply, fortunately we work out the solution. I recommend @slsongge close this issue.
