### ISSUE TITLE
Export in pdf and logo insertion

### ISSUE THREAD

**Issue by yg42** [jupyter/nbconvert#1301]
Hi all,

I wrote a custom tplx file for pdf export, and I want to add a logo on the generated files. I basically use these lines:

```
((* block packages *))
\usepackage{graphicx}
\graphicspath{{./}{../tmp/}}
\let\Oldincludegraphics\includegraphics
% Set max figure width to be 80% of text width, for now hardcoded.
\renewcommand{\includegraphics}[1]{\Oldincludegraphics[width=.8\maxwidth]{#1}}

\usepackage{tikz}
\usepackage{tikzpagenodes}
\usetikzlibrary{positioning}
\usepackage{eso-pic}
\AddToShipoutPictureBG{\begin{tikzpicture}[remember picture, overlay]%
\draw(current page footer area.south west) node[below right]{\Oldincludegraphics{logo.pdf}};
\end{tikzpicture}}%

((* endblock packages *))
```

The problem is that logo.pdf is not stored in the same folder as the ipynb notebook, and I cannot manage to define the correct location. I get a 
`LaTeX Warning: File 'logo.pdf' not found on input line...`

Is there a way, other than using `\graphicspath` with an absolute path, to handle the external folder for this image?

thank you in advance
best regards

**Comment by t-makaro** [comment]
It seems like this is more of a LaTeX question than an nbconvert one. You could convert the notebook to plain LaTeX and debug that and then if you can find something that works there then you can edit the template to match.

It looks like you are overwriting a bunch of the template which does include some critical code. You can use the super command to add to it instead of override.
```
((* block packages *))
((( super() )))
\graphicspath{{./}{../tmp/}}

\usepackage{tikz}
\usepackage{tikzpagenodes}
\usetikzlibrary{positioning}
\usepackage{eso-pic}
\AddToShipoutPictureBG{\begin{tikzpicture}[remember picture, overlay]%
\draw(current page footer area.south west) node[below right]{\Oldincludegraphics{logo.pdf}};
\end{tikzpicture}}%
((* endblock packages *))
```
As a warning though, the templates are being changed quite drastically in 6.0.

**Comment by yg42** [comment]
I solved this problem with an absolute path using the \string~ comment, for example:

\graphicspath{{.}{\string~/.jupyter/templates/}}
