### ISSUE TITLE
html_toc export - TOC is disappearing

### ISSUE THREAD

**Issue by stefansimik** [jupyter/nbconvert#1479]
Hi, 
TOC generated by html_toc is very unstable and easily disappears after a few clicks.
Same buggy behavior is reproducible:
*  on all browsers (Chrome, Firefox)
* and happens on all types of python notebooks

#### Steps to reproduce this issue?

Simply export any notebook with html_toc and click multiple times on the left side-bar, containing TOC.
It simply disappears after a few clicks and TOC is not available anymore.
You need to execute a hard-reload of webpage, to see TOC again.

#### Minimum notebook that reproduces this issue on conversion

(remove last suffix *.txt to get original file)

**Example 1**
* [test.ipynb.txt](https://github.com/jupyter/nbconvert/files/5628784/test.ipynb.txt) - simple Python notebook
* [test.html.txt](https://github.com/jupyter/nbconvert/files/5628818/test.html.txt) - export of notebook above

**Example 2**
* [Dashboard.html.txt](https://github.com/jupyter/nbconvert/files/5628846/Dashboard.html.txt) - export of more complex notebook

#### Screenshots
![screenshot](https://user-images.githubusercontent.com/6208056/100864725-b1f08200-3496-11eb-9a90-d5cfd0c2b9d7.png)

#### nbconvert version
**Nbconvert 5.6.1**

**Comment by MSeal** [comment]
First off apologies no one responded to this ticket in a timely manner.

Unfortunately this is likely an issue in https://github.com/ipython-contrib/jupyter_contrib_nbextensions. I'd open the issue on that project instead, though looking at the commit history work there hasn't had any changes since 2019, so the TOC extension might not be supported by anyone atm.

Going to close this issue since it's not related to the project, but I'll try to keep an eye if there's follow-up questions.
