### ISSUE TITLE
jupyter export error with table of contents

### ISSUE THREAD

**Issue by MKJJO** [jupyter/nbconvert#1500]
I am using jupyter nbconvert(nbextensions) It worked well in jupyter but I can't export to html with toc

I must to export to html with the format(including auto menu items). When I tried to export html with toc, a error message raised like bellow

```
File "/opt/anaconda3/lib/python3.8/site-packages/jinja2/loaders.py", line 429, in load
raise TemplateNotFound(name)
jinja2.exceptions.TemplateNotFound: toc2
```
I tried using terminal, but it didn't work. And I also checked toc2.tpl is exist but I found there are 2 files.

One thing is in "/Users/danna.cho/Library/Python/3.8/lib/python/site-packages/jupyter_contrib_nbextensions/templates"

Another thing is in "/opt/anaconda3/lib/python3.8/site-packages/jupyter_contrib_nbextensions/templates"

Is it problem? And I wondering sys.path has something wrong.

My sys.path is

```
'/opt/anaconda3/lib/python38.zip',
'/opt/anaconda3/lib/python3.8',
'/opt/anaconda3/lib/python3.8/lib-dynload',
'',
'/Users/danna.cho/.local/lib/python3.8/site-packages',
'/opt/anaconda3/lib/python3.8/site-packages',
'/opt/anaconda3/lib/python3.8/site-packages/aeosa',
'/opt/anaconda3/lib/python3.8/site-packages/IPython/extensions'
```
Please help me.

**Comment by gregnordin** [comment]
I'm observing the same behavior: nbconvert 6.0.7

Any ideas for how to fix? According to [Jupyter Notebook Download as html_toc Error](https://stackoverflow.com/questions/65376052/jupyter-notebook-download-as-html-toc-error), the error was fixed by downgrading to nbconvert 5.6.1. However, #1479 says that toc's generated with this version are unstable and can disappear after a few clicks in the toc.

**Comment by saebragani** [comment]
I face the same problem. Downgrading to nbconvert 5.6.1 solved the issue, but I need to use version 6 since version 5 does not work well with ipywidgets.

**Comment by MSeal** [comment]
This is likely an issue in https://github.com/ipython-contrib/jupyter_contrib_nbextensions not working with the new export template pattern from 6.0 release since the file involved is https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/master/src/jupyter_contrib_nbextensions/templates/toc2.tpl and it hasn't been touched since 2019. I'd open the issue on that project instead.

Going to close this issue since it's not related to the project, but I'll try to keep an eye if there's follow questions from other repo.

**Comment by MSeal** [comment]
Noticed that TOC hasn't been updated since 2019... not sure if there's any reconciliation for fixing on that end if there's no one actively maintaining that code.
