### ISSUE TITLE
SVG cleaning should not use HTML cleaner

### ISSUE THREAD

**Issue by akx** [jupyter/nbconvert#1894]
> The templates for actual `image/svg+xml` cells (e.g. https://github.com/jupyter/nbconvert/blob/a8067447af4a90690b762f48ceb46d40207a344e/share/templates/lab/base.html.j2#L166) should use an XML-savvy cleaner since a `image/svg+xml` is _not_ HTML to begin with. 

_Originally posted by @akx in https://github.com/jupyter/nbconvert/issues/1890#issuecomment-1293619627_
      

---

(I just wanted to make an issue out of this so it's searchable...)

**Comment by hadim** [comment]
I confirm that `| clean_html` render corrupted SVG (black background, deformed shapes, etc). When removing it the SVG is rendered correctly.

It happens when generating HTML MKDocs page with mkdocs-jupyter on SVG rendered with [data](https://github.com/datamol-org/datamol) and [rdkit](https://github.com/rdkit/rdkit).

**Comment by desilinguist** [comment]
I am also seeing the same issue in my nbconvert-ed HTML pages. See https://github.com/jupyter/nbconvert/issues/1849#issuecomment-1298985550

**Comment by therzka** [comment]
👋 Myself and a colleague have been looking into this as well. It looks like despite [this PR](https://github.com/jupyter/nbconvert/pull/1890) although the `style` attribute is allowed on valid SVG elements, SVGs still don't render because the value of the `style` attribute is stripped.

![image](https://user-images.githubusercontent.com/7219923/202018396-5a4958d6-3483-435d-916c-e176aabc8808.png)

Our current workaround is to revert back to the old sanitization behavior and define our own lxml.Cleaner() to override default_filters["clean_html"]:

```
cleaner = Cleaner(
    style=True,
    scripts=True,
    inline_style=False,
    safe_attrs_only=False,
    remove_unknown_tags=False
)
default_filters["clean_html"] = cleaner.clean_html
```

**Comment by stefmolin** [comment]
I'll also share my hack while we wait for a fix. Change `{{ output.data['image/svg+xml'].encode("utf-8") | clean_html }}` to just `{{ output.data['image/svg+xml'] }}` in `share/jupyter/nbconvert/templates/lab/base.html.j2` (this will be in your virtual environment).

**Comment by desilinguist** [comment]
I use `nbconvert` programmatically and so modifying the `base.html.j2` template, while effective, wasn't really an ideal solution for me. Here's the fix that worked for me. Basically, the goal is to turn the offending `clean_html` into a nop. To achieve this, I did:

```python
from nbconvert.exporters import HTMLExporter
from nbconvert.exporters.templateexporter import default_filters

def convert_to_html(notebook_file, html_file):

    def custom_clean_html(element):
        return element.decode() if isinstance(element, bytes) else str(element)

    default_filters["clean_html"] = custom_clean_html

    exportHtml = HTMLExporter(config=report_config)
    output, _ = exportHtml.from_filename(notebook_file)
    open(html_file, mode="w", encoding="utf-8").write(output)
```

This works for me with nbconvert=7.2.5.

**Comment by hadim** [comment]
Thanks for sharing this fix.

For people like me using it trough tan external library (to generate a documentation in my case with [mkdocs-jupyter](https://github.com/danielfrg/mkdocs-jupyter)), we will need that to be fixed in `nbconvert` directly.

**Comment by carlosefr** [comment]
This is also mentioned in #1863.

**Comment by josephmcasey** [comment]
Related to mkdocs-jupyter a consumer of nbconvert:
Thanks for writing that workaround @desilinguist . @hadim , I opened <PR> that leverages this solution for this mkdocs plugin, and it looks fully functional with the existing test suite. If you think you have a particularly complex SVG to render then it would be great to add your example to the repository.

Related to nbconvert:
As for this particular break, I think the obvious solution that would be suggested is that this library abide by the [W3 specifications for SVG](https://www.w3.org/TR/SVG/struct.html#SVGElement), so I will try to pose a question I think might be slightly more original and reduce the overall burden of overhead of library maintenance.

If this solution is not too lazy as to denigrate the character of the changeset author, would the maintainers find it an acceptable solution to introduce a github action that [renders the html produced on a headless browser like chrome](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-chrome.yml) as a form of validation testing? I ask because it seems like that would quickly outsource to Google and consumers of the library most of the complexity that would come with writing unit tests that cover the entire spectrum of [W3 Standards](https://www.w3.org/TR/). When a break is found by a consumer, grab their notebook and add it to the array of validation tests.

**Comment by yksantaro** [comment]
I have the same problem on &lt;xlink:href&gt; SVG attribute. (Ex. axes labels in matplotlib objects)
I think that inline SVG image data can be bypassed rather than processed by clean_html() because the most images will probably be displayed in JupyterLab window and will be exported and displayed correctly in HTML without any cleaning.

So I added bypass_svg() function for strings.py (in lib/python3.11/site-packages/nbconvert/filters) and related files: templateexporter.py (in lib/python3.11/site-packages/nbconvert/exporters) and base.html.j2 (in share/jupyter/nbconvert/templates/lab) as attached patches below.

[templateexporter.py.patch](https://github.com/jupyter/nbconvert/files/11387189/templateexporter.py.patch)
[base.html.j2.patch](https://github.com/jupyter/nbconvert/files/11387192/base.html.j2.patch)
[strings.py.patch](https://github.com/jupyter/nbconvert/files/11387195/strings.py.patch)

This work around is so fine for me.

**Comment by jstorrs** [comment]
I don't know if this is correct, but while researching methods to sanitize SVG [this site](https://digi.ninja/blog/svg_xss.php) was mentioned on security.stackexchange.com which suggests that SVG loaded via img tags won't execute scripts. Since the SVG is already inside an img tag, could we just base64 pack the SVG content?
