### ISSUE TITLE
Doc building instructions

### ISSUE THREAD

**Issue by tritemio** [jupyter/nbconvert#192]
The instructions are missing the pandoc dependency.

Also, should the requirements point to the released PyPI ipykernel, instead of the github version?

**Comment by willingc** [comment]
@tritemio Thanks for the questions. The installation docs cover the pandoc dependency (https://github.com/jupyter/nbconvert/blob/master/docs/source/install.rst) though it's a good idea to add it to the docs/README.md file.

As for the docs/requirements.txt file, I think its fine to use the github version since the requirements are only used for building the docs. If you or @takluyver feel strongly about using the released version, I'm cool with that for the time being as well.

**Comment by takluyver** [comment]
Now that we use nbsphinx, pandoc is no longer required to build the docs. And the requirements.txt does now refer to the released version of ipykernel rather than installing from Github.
