### ISSUE TITLE
Attempting to convert a notebook with pasted image to PDF fails with an error

### ISSUE THREAD

**Issue by andrii-i** [jupyter/nbconvert#1977]
Attempting to convert a notebook with pasted image to PDF fails with an error in both Jupyterlab and Notebook head-of-master. 

## Reproduce

1. Create a notebook.
2. Copy an image and paste it into the markdown cell.
3. Attempt File->Save and Export Notebook As ...->PDF

- Created based on jupyter/jupyterlab#14365 by @frohro

![image](https://user-images.githubusercontent.com/26686070/232924319-4c5d33d2-046e-45ce-8db6-e296b94cdbfc.png)

**Comment by tuncbkose** [comment]
As far as I can tell, the problem is that the pasted image is stored directly in the notebook, base64 encoded (according to [this](https://nbformat.readthedocs.io/en/latest/format_description.html#cell-attachments)). 

It shouldn't be too difficult for `nbconvert` to look for these attachments and convert them into files in the same directory, so that outputs like markdown and latex will work properly.
