### ISSUE TITLE
Error 404 No such file or directory

### ISSUE THREAD

**Issue by AlexGriffiths526** [jupyter/nbconvert#2031]
Jupiter Lab 4.0.2

When I try to save and export the notebook as HTML or any other format I get a 404 error. Below is the output in from Anaconda Prompt.

[W 2023-08-04 11:47:19.166 ServerApp] 404 GET /nbconvert/HTML_NoInput/RTC%3ATest.ipynb?download=true (::1): No such file or directory: RTC:Test.ipynb
[W 2023-08-04 11:47:19.169 ServerApp] 404 GET /nbconvert/HTML_NoInput/RTC%3ATest.ipynb?download=true (0043a24c16a345a9a677f3d39b54e503@::1) 203.16ms referer=http://localhost:8888/lab/tree/RTC%3ATest.ipynb

In the above my notebook is called Test.ipynb

I have tried removing and reinstalling nbconvert but no luck. It seems to suggest that the notebook does not exist. I have tried on various notebooks stored in different file locations but I have the same issue. Any help anyone could offer would be greatly appreciated.

**Comment by tuncbkose** [comment]
Looks like https://github.com/jupyterlab/jupyter-collaboration/issues/151

**Comment by AlexGriffiths526** [comment]
Thanks for the response. This does look like the same issue. I will close this one.

**Comment by f14h** [comment]
Please reopen this issue. See also the recent discussion in https://github.com/jupyterlab/jupyter-collaboration/issues/183. This seems to be very much an issue of nbconvert (as it can't deal with custom drives) and not jupyter-collaboration.

**Comment by tuncbkose** [comment]
Thank you for linking the discussion above @f14h, I didn't know about the custom drive mechanism before. That said, I still think the issue lies not with nbconvert. Having read the discussion above, I believe a better place to fix this problem is the JupyterLab component that calls nbconvert (somewhere in [here](https://github.com/jupyterlab/jupyterlab/blob/main/packages/services/src/nbconvert/index.ts) maybe?).

While it may be relatively easy to check if a given filename starts with `RTC:` and if so strip it, fixing it in JupyterLab seems more principled and robust for other custom drives (and also consistent with [this comment](https://github.com/jupyterlab/jupyter-collaboration/issues/151#issuecomment-1562367129)).

This is of course only my opinion, I am happy to hear more from others. However, I am reluctant to reopen the issue now given my reasoning above, unless there is more interest/discussion (or someone else decides to do it).
