### ISSUE TITLE
--to notebook removes newline at end of file

### ISSUE THREAD

**Issue by amueller** [jupyter/nbconvert#207]
When I run the following on a notebook:
```
jupyter-nbconvert --ClearOutputPreprocessor.enabled=True --to notebook --inplace *.ipynb
```
it removes the newline after the last ``}``.

That is a bit of an inconvenience, since that changes all notebook files, even if they were cleared already.
I'm running version 4.1.0

**Comment by takluyver** [comment]
Should be an easy fix in `NotebookExporter` - do you want to make a PR?

**Comment by amueller** [comment]
I'd love to but probably not any time soon.

**Comment by amueller** [comment]
stupid question: shouldn't this be fixed in nbformat?

**Comment by takluyver** [comment]
`nbformat.write()` does already add a newline to the end - when saving a notebook, that's what is used. However, when using nbconvert to a notebook, it uses `nbconvert.writes()` to generate a string, and writes that to a file separately. So this could be fixed by:

1. Ensuring the newline is there in nbconvert as well.
2. Moving the 'check there's a newline' code from `nbformat.write()` to `nbformat.writes()`.

I think I prefer 1 - the final newline is specifically relevant when writing to files, and there may be contexts where you don't want it. I don't feel strongly, though - it's easy enough to `.rstrip()` it off again if you don't want it there.

**Comment by amueller** [comment]
so the result of ``writes`` will never have a trailing ``\n``? Then I'd just add one to ``output``. Or should there be a check if there's a trailing ``\n`` and only append one if not so?

[Sorry for stupid questions. I haven't really looked inside notebook and nbconvert before]

**Comment by takluyver** [comment]
I'd do the check. The result of writes probably won't have a trailing `\n`, but it's cheap to check, and it means we can never have a situation where it's adding one more newline every time you process the notebook.
