### ISSUE TITLE
ExecutePreprocessor.timeout does not work as expected

### ISSUE THREAD

**Issue by jlamcanopy** [jupyter/nbconvert#234]
In the documentation, it says ExecutePreprocessor.timeout is "The time to wait (in seconds) for output from executions"

My observation is that even the cell takes 1 second, it will wait until the timeout expires before moving to the next cell. It does not seem to be right because most of the cells take seconds only a few take longer. Is that something I'm missing here?

**Comment by takluyver** [comment]
If that's what you're seeing, that's a bug. If a cell finishes in 1 second, it should notice that immediately and execute the next cell.

Is there anything unusual about your setup that might relate to this? E.g. are you using a different kernel?

**Comment by jlamcanopy** [comment]
@takluyver Thank you for the quick reply. You are right! I'm not using a python kernel. I'm using a kernel called ispark. Are you suspecting it is the kernel issue?

**Comment by jlamcanopy** [comment]
@takluyver You are right. If I tested it with a python kernel, it behaves as described. 
I used ispark kernel for long time interactively and I never encountered issues before. Do you have a clue why it behaves strangely with nbconvert?

**Comment by takluyver** [comment]
I'd guess that it's not sending the kernel status messages:
http://jupyter-client.readthedocs.org/en/latest/messaging.html#kernel-status

The execute code in nbconvert looks for a *kernel idle* message to tell it that there's no more output. If it doesn't see that, it will wait for the full timeout again. We can probably make that timeout shorter, because it's collecting the outputs after it's received `execute_reply`, which should already mean that execution has finished.

**Comment by minrk** [comment]
Yeah, it's probably a good idea to have a long-ish (~30 second) timeout for the execute_reply, and then a relatively short timeout for the output (~5s, conservatively), since it's just waiting for network funny business.

But this behavior does mean that the ispark kernel is not following the messaging protocol correctly.

**Comment by jlamcanopy** [comment]
Thanks guys! I'm going to make some changes to ispark to see if I could make it to conform to the messaging protocol.

**Comment by jlamcanopy** [comment]
@takluyver Sorry about bothering you but my knowledge in the protocol is quite limited but I want to fix ispark so I can use nbconvert with it. I found the code that might cause the issue you mentioned:

```
def busy[T](block: => T): T = {
    send_status(ExecutionStates.busy)

    try {
      block
    } finally {
      send_status(ExecutionStates.idle)
    }
  }
```

It looks like it only send IDLE messages after the 'block' of code finish execution. From what I understood the status should be sent for every message not just the execution. I don't understand the difference between "message" and "execution". Can you give me a quick hint on it?

**Comment by takluyver** [comment]
A message is any communication between the frontend and the kernel. For instance, when you press tab, the frontend sends a `complete_request` message to the kernel, and the kernel - if it implements completion - works out the possible completions and sends back a `complete_reply` message with that data.

The most important message is `execute_request`, which the frontend sends when it wants code to be executed.

Besides the various request & reply messages, there is a second ZMQ socket for output messages, e.g. when your code does `print('hi')`, it generates a `stream` message. We call this the iopub socket. The kernel busy/idle status messages are also sent over this socket. It probably makes sense to send these status messages for any request-reply message, but it's most important for execution, because that's most likely to take an appreciable amount of time.

The message spec document has much more info about all this:
http://jupyter-client.readthedocs.org/en/latest/messaging.html

**Comment by minrk** [comment]
Yup, the general flow is:

1. request arrives
2. send status: busy on iopub
3. process request
4. send reply
5. send status: idle on iopub

And that should be true for handling *all* request/reply events.
