### ISSUE TITLE
nbconvert to pdf fails for $\LaTeX$ in markdown

### ISSUE THREAD

**Issue by jankoslavic** [jupyter/nbconvert#262]
To reproduce the error: try to convert a simple document having $\LaTeX$ in the markdown.

**Comment by takluyver** [comment]
What error do you get?

**Comment by jankoslavic** [comment]
I get the following:

    LaTeX Warning: No \author given.

    ! You can't use `\spacefactor' in math mode.
    \@->\spacefactor
                     \@m
    l.252     \(\LaTeX
                      \)
    ?
    ! Emergency stop.
    \@->\spacefactor
                     \@m
    l.252     \(\LaTeX
                      \)
    !  ==> Fatal error occurred, no output PDF file produced!

**Comment by mgeier** [comment]
The macro `\LaTeX` doesn't work in math mode, that's why you get the error.
However, MathJax (that does the rendering of equations in HTML output), allows that although it's normally *only* using math mode.

If you use `\LaTeX` (without surrounding `$` signs), this will not be rendered correctly in HTML output, but it will work in LaTeX output.

If you want it to work in both, you should use `$\mathrm{\LaTeX}$`, which switches to text mode within math mode.

**Comment by jankoslavic** [comment]
Thanks for the comment. @mgeier

**Comment by jolars** [comment]
`$\mathrm{\LaTeX}$` still produces an error for me. `$\text{\LaTeX}$` works for me, however.

**Comment by SunilSimha** [comment]
@mgeier using `$\mathrm{\LaTeX}$` still produces the same error when downloading as PDF. Is there another way for it work in both HTML and PDF?

**Comment by michaelpacer** [comment]
I think that's correct.

**Comment by michaelpacer** [comment]
@SunilSimha Thanks for pointing this out. 

`$\mathrm{foo}$` just sets the text `foo` as roman font, it doesn't switch it out of math mode.

So even using `$\mathrm{\LaTeX}$` won't work, since it doesn't exit math mode. 

You could use makebox (which will switch to text mode) `$\mbox{\LaTeX}$` but, that won't work in html or in the notebook. It looks like this is a MathJaX decision to not support text mode but only math mode: https://github.com/mathjax/MathJax/issues/569. 

@takluyver @Carreau any thoughts on how to address this?

**Comment by Carreau** [comment]
Well, if MathJax does not support it, then I guess we don't. 

We have a limited amount of bandwidth so for many feature unfortunately the answer will be that we would like to, but for now we won't as it is too complicated/too much maintenance. 

For now I would task this as : Document better in known limitations.

**Comment by michaelpacer** [comment]
Verified: 

\mathrm, \rm, and no command work in MathJax, not in LaTeX.

\mbox, \text don't work in MathJax, do in LaTeX. 

Just found it: they redefine `\LaTeX` here: https://github.com/mathjax/MathJax/blob/master/unpacked/jax/input/TeX/jax.js#L972

**Comment by michaelpacer** [comment]
We don't have a known limitations section in the docs… where would that normally go?

**Comment by Carreau** [comment]
> We don't have a known limitations section in the docs… where would that normally go?

I'm going to be useless and say "in the right location" ?

Joke aside I would do a 2nd level section that can be seen in the sidebar. You can use `:gh:` in rst to link to github issues. The other possibility is in the release notes per versions.

**Comment by mgeier** [comment]
Indeed, `$\mathrm{\LaTeX}$` produces this error:

```
! You can't use `\spacefactor' in math mode.
\@->\spacefactor 
                 \@m {}
l.3 $\mathrm{\LaTeX}
                    $
```

However, if I force compilation, the resulting PDF looks fine. That's probably why I missed the error last time.

As @michaelpacer mentioned, `$\text{\LaTeX}$` works in LaTeX but not in MathJax.

I would say that's actually a bug in MathJax's implementation of `\text{}` then. But since MathJax doesn't intend to be a full LaTeX renderer, it shouldn't be surprising that most non-math things don't work.
I think the original mistake of MathJax was to support `\LaTeX` in the first place, because it simply doesn't make sense in math mode.

Now that's too late, I suppose the next best thing would be to ask the MathJax people to support `$\text{\LaTeX}$` as some kind of a special case.

The simpler solution would be just to avoid using `\LaTeX` and use plain old LaTeX. I think that still everyone will understand what you're talking about.

**Comment by michaelpacer** [comment]
MathJaX  doesn't have an implementation of text; they are directly
redefining the command to work in math mode.

We could redefine it too as part of our preamble,  but what I'd ideally
like to do is to be able to mirror the command in math mode so that it
treats it in math mode as though it were `\text{\LaTeX}`. but I can't
figure out how that modality specific shadowing would work.

**Comment by jfburkhart** [comment]
Seems this issue is still open, but the conversation has stalled. Are there any plans to address this?

**Comment by jankoslavic** [comment]
Hi! It is like a "hello world" of showing that Latex works:) It should be addressed. :)

**Comment by mgeier** [comment]
It was a mistake of MathJax to support `\LaTeX` in the first place, since it is not a math mode command. If they want to make up for it, they should support `$\text{\LaTeX}$` as a special case (which `nbconvert` will handle without problems).
This is a MathJax issue, not a `nbconvert` issue. `nbconvert` should not jump through hoops to make such an ill-conceived feature possible.

**Comment by wstomv** [comment]
From the user perspective, this is a Jupyter-related issue. (And an easy fix is suggested below.)

The Jupyter project chose to use MathJax. Users will want $\LaTeX$ in their notebooks, and that works in the Jupyter Notebook Editor, thanks to MathJax. Conversion to tex and pdf should also be made to work. The spec of MathJax is known; it does not offer a pathway to tex and pdf.

So, the place to make conversion to tex work is in the Jupyter system.

I suggest to add to the preamble of the generated tex file a redefinition of `\TeX` and `\LaTeX` (and possibly some other stuff as well). The current preamble already contains a lot of similar things that are needed to make it work in the Jupyter way. In particular, there is already a section:
```tex
    % Math Jax compatability definitions
    \def\gt{>}
    \def\lt{<}
```

(Please, also fix the typo in 'compatability', while you are at it.)

Adding the following two lines fixes the problem with `\TeX` and `\LaTeX`:
```tex
    \def\TeX{\mbox{T\kern-.14em\lower.5ex\hbox{E}\kern-.115em X}}
    \def\LaTeX{\mbox{L\kern-.325em\raise.21em\hbox{$\scriptstyle{A}$}\kern-.17em}\TeX}
```

Note that compared to what MathJax itself defines, I had to add `\hbox` and `$`s to make it work.

Since the use of `\LaTeX` is very visible (anyone demonstrating Jupyter notebooks with LaTeX will use it), this is an urgent problem.

**Comment by t-makaro** [comment]
If MathJax supports $\LaTeX$ by redefining it, then we should redefine it accordingly to support it. I've tested adding the 2 extra lines provided by @wstomv, and it appears to work as expected. I believe someone just needs to submit a pull request for it.

**Comment by cemanughian** [comment]
@wstomv  Which file did you add those two lines to fix it?

**Comment by wstomv** [comment]
@cemanughian In the file `base.tplx` in `nbconvert/templates/latex/base/` after installation. In the repo, it appears to be in `nbconvert/templates/latex/base.tex.j2`.

It seems this is fixed (in a different way) in my currently installed version `nbconvert` 5.4.1 (together with the typo). I noticed the problem in version 5.3.1.
