### ISSUE TITLE
raise TypeError("Inkscape svg to pdf conversion failed")

### ISSUE THREAD

**Issue by charlesdavid** [jupyter/nbconvert#302]
Not sure why I can not use jupyter nbconvert to get a pdf... and why there is a reference to a stand alone application Inkscape? I need to share my notebooks with collaborators in and easy way. Those folks think advanced programming is opening Excel. I can not save notebooks larger than 50mb, which eliminates all graphical output. So, I need a turnkey solution to output the entire NB, graphics and all, and send it to the other folks. What is the EASY-SIMPLE-SOLUTION_WORKABLE to share NBs that have embedded graphics and thus are 100mb or more?

**Comment by takluyver** [comment]
Inkscape is used if there are SVG images, because those can't be used directly in Latex (as far as I know), so they have to be converted to a format that can. Inkscape is the most practical way we know to do that.

In general, I think the 'easiest' format to convert to for sharing is HTML - that doesn't require any external programmes to help with the conversion. It may be a bit slow with large notebooks with a lot of embedded images, though.

**Comment by methodds** [comment]
The same happens when trying to convert R notebooks with the IR Kernel to PDF. I usually also prefer HTML, but this does not work well with the R kernel either (the plots are sometimes cutoff, sometimes empty).

**Comment by janschulz** [comment]
For irkernel, try running 

```R
options(jupyter.plot_mimetypes = c("text/plain", "image/png" )) # no more svg...
```

This removes svg from the produces images...

**Comment by soamaven** [comment]
Should `.svg` conversion be transparent when using `jupyter nbconvert --to pdf My_Notebook.ipynb`? I am getting the same error as in title, and I definitely have inkscape in my path.

getting:
```! LaTeX Error: Unknown graphics extension: .svg.```
presumably from pandoc

**Comment by takluyver** [comment]
Is there any error message from Inkscape that might indicate what went wrong? We raise the error in the title when the output file we asked Inkscape to create is not present.

**Comment by soamaven** [comment]
I apologize, I actually do not get that specific error, I am getting the error that `.svg` cannot be converted. I meant "same error" as in "I have a similar problem". My apologies for the miscommunication, I'll aim to be more precise next time.

I get no errors from Inkscape at all.  The only error I get is 
```! LaTeX Error: Unknown graphics extension: .svg.```
and then the conversion bows-out. It should be able to find it:
```
which inkscape
/usr/bin/inkscape
```

**Comment by takluyver** [comment]
Yes, SVGs should be converted automatically. If it was failing to find inkscape, you would get a different error ("Inkscape executable not found"). The automatic conversion currently only works for SVG outputs, however - SVGs in markdown cells are not handled.

**Comment by soamaven** [comment]
Ahh. This is the issue then -- the `.svg` files are referenced in markdown cells.

**Comment by mseri** [comment]
I have been hit by the same "missing inkscape" issue. Both `convert` from imagemagick and `rsvg-convert` can convert svg to pdf, would you be interested into a PR that checks if any of those is available for the conversion?

**Comment by mgeier** [comment]
As an alternative, when using `nbsphinx` to generate the LaTeX/PDF output, the existing Sphinx infrastructure can be used to automatically convert SVG images to PDF images, see https://nbsphinx.readthedocs.io/en/latest/markdown-cells.html#SVG-support-for-LaTeX.

At some point this will hopefully also be available on readthedocs.org, see https://github.com/rtfd/readthedocs-docker-images/pull/79.

**Comment by terminal-w** [comment]
Would it be possible to update `svg2pdf.py` so that it checks the System Path for Inkscape before the Registry? I can't find how to check if a shell command will execute without actually executing it.

With the latest install of inkscape `HKEY_LOCAL_MACHINE\\SOFTWARE\\Classes\\inkscape.svg` does not exist in my registry.
The only registry reference I have for inkscape is : `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\App Paths\inkscape.exe`
I think more windows users are comfortable to edit the system path especially if they want their anaconda distro to be accessible to other apps or at least the path is less scary than the registry.

**Comment by t-makaro** [comment]
A few different issues are present on this thread. I'm going to close this issue in favour of some other individual issues to help us organize this better. If your SVG issue does not fall into one of the following issues, then please open a new issue.

#885: Allow an alternative/fallback to inkscape.
#244: SVG images in markdown not converted.
#585: Inkscape not found when in system path.
