### ISSUE TITLE
Markdown image extraction issues

### ISSUE THREAD

**Issue by amueller** [jupyter/nbconvert#342]
I'm trying to convert to markdown, and there seems to be some issues with the image extraction.
It looks like they are always extracted properly, but sometimes no reference is added to the text.
I think this is the case when both PNG and PDF are embedded.

For example for this file:
https://github.com/amueller/introduction_to_ml_with_python/blob/master/02-supervised-learning.ipynb

Or maybe pdf is never embedded in markdown? Should it be converted to SVG?
Or maybe rather: if pdf and png are present, and pdf is not supported, shouldn't it pick up png?

**Comment by willingc** [comment]
@minrk @takluyver @Carreau We've been discussing this on gitter. @amueller is using master of nbconvert and pandoc pandoc 1.16.0.2.

From Gitter:
again, nbconvert question: is there something to extract figure so that they can be embedded in markdown? Currently the markdown conversion doesn't seem to be doing that and just drops figures entirely

Carol Willing @willingc 16:31
Hi @amueller, Nice working with you at SciPy. Perhaps try a preprocessor http://nbconvert.readthedocs.io/en/latest/api/preprocessors.html#nbconvert.preprocessors.ExtractOutputPreprocessor

Andreas Mueller @amueller 16:31
Thanks  hm yeah that one is called and the files are generated, but somehow the code to include the image is not generated in the markdown...
hm it seems to work... sometimes

Carol Willing @willingc 16:35
Hmm...which version of nbconvert?
Intermittent problems are a favorite  Feel free to file an issue with whatever details that you have. Thanks!

Andreas Mueller @amueller 16:39
master

Carol Willing @willingc 16:43
Thanks, was hoping it was something other than master.
@carreau @takluyver @minrk Have you seen this behavior ^^ with nbconvert?

Andreas Mueller @amueller 16:46
I'll try it with a vanilla config first. Maybe my custom preprocessors are messing things up
hm with the vanilla config, it looks like it doesn't work if both svg and png are present

Andreas Mueller @amueller 16:57
ah. I think it doesn't include PDFs?
I generate pdf and png from matplotlib, and I guess it doesn't like the pdf?
shouldn't it use the png then?

Carol Willing @willingc 16:58
I seem to remember some issue with pdf. It's a separate conversion option. Let me go look at the docs.

Andreas Mueller @amueller 17:00
hm but I feel if there are png and pdf and the markdown output doesn't allow pdf embeddings, it should pick the png...

Carol Willing @willingc 17:01
Just out of curiousity what version of pandoc is installed?

Andreas Mueller @amueller 17:01
pandoc 1.16.0.2

**Comment by minrk** [comment]
PDF isn't supported in markdown output, but the default behavior is definitely supposed to be including png if it's present. We'll need to check the output selection code for why it's ignoring png output if that's what is happening.

**Comment by btel** [comment]
@willingc I am trying to find this conversation in Gitter chat. In which channel should I look for it?

**Comment by willingc** [comment]
@btel https://gitter.im/jupyter/notebook

**Comment by amueller** [comment]
@minrk I'm happy to take a look if you tell me where.

**Comment by willingc** [comment]
@minrk Wondering if ``ConvertFiguresPreprocessor`` shouldn't be listed in the defaults here:
https://github.com/jupyter/nbconvert/blob/master/nbconvert/exporters/exporter.py#L70

and possibly here too:
https://github.com/jupyter/nbconvert/blob/master/nbconvert/exporters/latex.py#L53

**Comment by amueller** [comment]
@minrk can you maybe point me where to look for which format is selected?

**Comment by minrk** [comment]
@amueller got it. `display_data_priority` defines the priority of display-data mime-types to include in a given output. There's a [base definition](https://github.com/jupyter/nbconvert/blob/cc7a2dd7ccb430c3545b153a5790cf7c289eb4e3/nbconvert/utils/base.py#L16) that should be overridden in most exporters. See [html](https://github.com/jupyter/nbconvert/blob/cc7a2dd7ccb430c3545b153a5790cf7c289eb4e3/nbconvert/exporters/html.py#L41) for example. Markdown should have a similar spec, [but doesn't](https://github.com/jupyter/nbconvert/blob/cc7a2dd7ccb430c3545b153a5790cf7c289eb4e3/nbconvert/exporters/markdown.py#L33).

The result is that the pdf output is selected as higher priority than png, but since PDF is not supported, no output is displayed. Adding the correct display priority to the MarkdownExporter should fix it.

@willingc I don't think so. ConvertFigures is an incomplete base class. SVG2PDF is a derivative, which is included in latex output.

**Comment by amueller** [comment]
awesome, thanks. I''ll look into it today.
