### ISSUE TITLE
Where to specify custom template file?

### ISSUE THREAD

**Issue by choldgraf** [jupyter/nbconvert#391]
Say I've got a template file that I've created on my own, is it possible to pass this to `--template=` without putting it in the templates folder? I haven't been able to find any information online about this. Otherwise, what's the recommended way to use your own template file? I'd like to use one that's located in a different folder from the default templates path.

**Comment by michaelpacer** [comment]
So I'm not sure about how to use this information yet, but this is probably going to be helpful. 

It looks like the template path is set here https://github.com/jupyter/nbconvert/blob/master/nbconvert/exporters/templateexporter.py#L110

    template_path = List(['.']).tag(config=True, affects_environment=True)

with the default being:

    default_template_path = Unicode(
        os.path.join("..", "templates"), 
        help="Path where the template files are located."
    ).tag(affects_environment=True)

And here is a case where the skeletons are added to the path:

    template_skeleton_path = Unicode(
        os.path.join("..", "templates", "skeleton"),
        help="Path where the template skeleton files are located.",
    ).tag(affects_environment=True)


which suggests that you might be able to include something like

    template_custom_path = Unicode(
        os.path.join("relative", "path", "declaration"),
        help="Path where the custom template files are located.",
    ).tag(affects_environment=True)

as part of your nbconvert configuration might work. 

The question is whether there is an easy way to access that api via the command line. My guess is the hooks are there, I just haven't figured out how to do that yet. My guess is that you tried including a full absolute pathname to the `--template` flag and that that didn't work. That wouldn't be surprising to me. But I don't know if there is a similar --templatepath flag that will allow you to add one interactively.

**Comment by michaelpacer** [comment]
@takluyver I feel like you would have a clear idea about the current state of the art on this issue and whether I've described it accurately.

**Comment by choldgraf** [comment]
yep - specifying a full path doesn't work because it assumes you're giving a file name + a default path. Since it's already using a for loop to try different combinations of template names etc, maybe a simple solution would be one final attempt to load the file by treating it as a raw file path before throwing the error?

**Comment by michaelpacer** [comment]
Aha. I did some more digging. You should be able to use the config file to already do this. 

https://nbconvert.readthedocs.io/en/latest/config_options.html

Specifically by changing `TemplateExporter.template_path` to include the path you need. 

probably can be done by the command line, but is safer to append to the list, by doing something like that described here: https://github.com/jupyter/nbconvert/blob/master/docs/source/usage.rst#converting-multiple-notebooks

list in a configuration file, say mycfg.py, containing the text:

```python
import os

c = get_config()
custom_path = os.path.join("..","relative","path","to","custom","dir")
c.TemplateExporter.template_path.append(custom_path)
```

and using the command:

```bash
$ jupyter nbconvert --config mycfg.py
```

if you want it to be universally available you could just add that to `~/.jupyter/jupyter_nbconvert_config.py` as stated at the top of the page.

You could probably set the value of the template path directly from the command line, but I think that might prove counterproductive since it's expecting a list of strings, not a string per se.

Anyway, does this solution work for you?

**Comment by choldgraf** [comment]
So I agree that it is possible to do this w/ the steps you just mentioned. That said, the reason I opened the issue is because that's a lot of work just to link to a template that's not on the default path. At that point it'd probably just be easier for me to copy a version of the template into the default folder.

The reason I'm looking for a simple solution is that I was hoping to be able to package a template along with a tiny python module that converts jupyter notebooks into an HTML format that works more nicely with blogging platforms like wordpress.

I was hoping to do all of the work under-the-hood with nbconvert templates, but it's way too much of a hassle to tell people "first you have to edit a bunch of config files". I want to be able to say "just download this module, run `python convert_to_html.py myfile` and it'll magically spit out an HTML file you can copy/paste into wordpress."

**Comment by choldgraf** [comment]
I suspect that another way to do this would be to use `nbconvert` as a python module rather than a command line tool, but I haven't found a lot of good documentation on how to do this.

**Comment by michaelpacer** [comment]
I think you'll want to do this using an exporter rather than just a template then, and then you can be the first person (that i know of, at least) to use the new entrypoints support as part of a 3rd party library! :D

that way you could have people download your package from pypi, and then just tell them which new exporter to use, wouldn't that fit your use case even better?

**Comment by michaelpacer** [comment]
@takluyver Is it possible to link to a different template, if not a different exporter using entrypoints?

@choldgraf do you have an example of your template working anywhere?

**Comment by choldgraf** [comment]
I can look into exporters, where's a good place to start looking?

re: an example, it is really a *very* simple extension of the basic HTML template. Just a few formatting CSS rules to make the output prettier, but not as much spacing / margins / etc that the full non-basic HTML template uses.

**Comment by minrk** [comment]
Perhaps if a template is given by absolute path, we could add its directory to the template_path so that it is found on template_path.

Something along the lines of:

```python
def _template_file_changed(self, change):
    path = change.new
    if os.path.isabs(path):
        template_dir, filename = os.path.split(path)
        self.template_path.insert(0, template_dir)
        self.template_file = filename
```

**Comment by michaelpacer** [comment]
@choldgraf  Sidenote: for what you were originally asking for if you're ok with people just downloading a module into their working directory, why doesn't just including the template file in the working directory and then running `jupyter nbconvert --to html --template=my_template.tpl 'nb.ipynb'`?  Based on https://github.com/jupyter/nbconvert/issues/206 and some quick testing of my own that seemed to work.

**Comment by michaelpacer** [comment]
@minrk I don't fully see how this would solve the problem, where would the `change` argument be defined so as to make sure that `change.new` had the right value? 

Also, where would this be added in the current codebase? or would it be defined in the external library that included the template?

**Comment by minrk** [comment]
This is a traitlets callback. When a trait is changed, a callback fires, with a [single change argument](http://traitlets.readthedocs.io/en/stable/api.html#callbacks-when-trait-attributes-change). This is already triggered now, when a user specifies a value `template_file`. The above code would do:

1. the user specified a custom template file
2. check if they specify an absolute path (perhaps better to use an `isfile` check?)
3. if so, put the directory containing the template on template_path, and use the base name for template_file, so that it's found by jinja's machinery

**Comment by minrk** [comment]
#398 allows you to do `--template /any/path/to/template.tpl`, adding the directory to template_path if it isn't there already. No additional explicit config of template_path is required.
