### ISSUE TITLE
What is this warning and what should we do about it?

### ISSUE THREAD

**Issue by michaelpacer** [jupyter/nbconvert#397]
DEPRECATION: Uninstalling a distutils installed project (nbconvert) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.

What is failing to be uninstalled by the current command? Can we fix this? Will this no longer be an issue since we're using setuptools?

Context: 
It would be nice to have a clean set of instructions on how to get an environment that pulls from the master branch to see if it solves people's problems. 
Thus, I'm trying to debug how upgrading to the master branch would work if you started from a standard install of `jupyter` via `conda`.

Part of the issue seems to arise from the fact that the easiest way to install the master branch relies on `pip install` and people using Anaconda are likely to be starting from a state brought about by `conda install` and there can be some wonkiness jumping back and forth between them. 

    conda create -n test_conda_pip python=3
    source activate test_conda_pip 
    conda install jupyter
    pip install -U git+https://github.com/jupyter/nbconvert@master

After which that warning comes up.

Also concerning is the fact that when this is done and I run `conda list` I get

>     nbconvert                 4.2.0                    py35_0    conda-forge
     ⋮
>     nbconvert                 5.0.0.dev0                <pip>

Which seems problematic. This may be an issue for the conda project, but it also might not be problematic but I'm not sure how really to test for where errors would crop up because of this.

**Comment by takluyver** [comment]
It's a warning pip gives. The conda build was done without generating pip/setuptools metadata, so pip sees it but can't confidently uninstall it. The fix is to use `pip install .` in the conda build instead of `python setup.py install` (the former command is now universally preferred to the latter, AFAIK).

Min has already made the change in the [conda-forge recipe](https://github.com/conda-forge/nbformat-feedstock/blob/4f4c4b33f57c03b77056ae8960b91c1dcc2a509f/recipe/meta.yaml#L14), but the version in Anaconda is built separately by Continuum, at least for now.
