### ISSUE TITLE
Module exports functions with naming conflict with submodule.

### ISSUE THREAD

**Issue by Carreau** [jupyter/nbconvert#415]
in short `nbconvert.exporters.export` is both a module and a function leading to some confusing situation (for @michaelpacer) where import get confused when using relative import and some things make no sens:

```
In [10]: from nbconvert.exporters.export import ExporterNameError

In [11]: import nbconvert.exporters.export as e; e
Out[11]: <function nbconvert.exporters.export.export>
```

Wait did I just import a class from a function , and is the function it's own module ?

Proposed fix:

Rename the module `nbconvert.exporters.export` to something else. Deprecate and shim it (not to break import) 

That's not an hard issue to fix, but it's an interesting one. I'm fine doing it, but we can leave it for someone who is interested in it and weird python import behavior.

**Comment by michaelpacer** [comment]
I think in my case in #414, it wasn't this issue because I was using
relative imports which should only work on modules/packages and not
functions as the argument after `from` (e.g., `from .export`).

I think fixing the name ambiguity is probably a good idea, but I think I
was running into a cyclic dependency issue which was solved by moving the
import inside of a function rather than at the top level (like the codebase
was already doing with  `from .export import get_exporter` a few lines
before my changes). I can see reason to get rid of this as well, but I
think fixing this kind of cyclic dependency in a non code-duplicating way
is going to be a to require isolating  some of the exporter declaration
functionality from the exporter getting(and erring) functionality in
separate modules.

**Comment by michaelpacer** [comment]
#423 closes this.
