### ISSUE TITLE
General import statement audits

### ISSUE THREAD

**Issue by michaelpacer** [jupyter/nbconvert#424]
Need to go through to check for import statements that are hiding within functions

- [x] nbconvert/nbconvert
- [x] exporters
- [x] filters
- [x] postprocessors (3 ?s found)
- [x] preprocessors (4 ?s found)
- [x] ~~resources (mostly empty)~~
- [x] ~~templates (no `.py` files)~~
- [x] tests (1 ? found)
- [x] utils
- [x] writers

**Comment by michaelpacer** [comment]
https://github.com/jupyter/nbconvert/blame/master/nbconvert/tests/base.py#L127

inside `_get_files_path()` we import `nbconvert`

What is the reason for this being there rather at the top of the file? Is there a reason relative imports are bad for this? Would some kind of cyclic dependency would arise if you tried to use restricted absolute import (`import __file__ from nbconvert as file_path_id`)?

cc: @minrk

**Comment by michaelpacer** [comment]
The resources directory is empty but for an empty `__init__.py`. I'm assuming that we populate it dynamically. However, I am still confused as to it's aim.

cc @minrk

**Comment by michaelpacer** [comment]
https://github.com/jupyter/nbconvert/blob/master/nbconvert/preprocessors/latex.py#L43

In the LaTeX preprocessor `preprocess` function we `import LatexFormatter from pygments.formatters`, is there a reason this cannot be done at the top of the page? 
This seems like something that we can move without issue. 

cc @minrk

**Comment by michaelpacer** [comment]
https://github.com/jupyter/nbconvert/blob/master/nbconvert/preprocessors/execute.py#L166

In the execute preprocessor `preprocess` function we `from jupyter_client.manager import start_new_kernel`. Is there a hidden cyclic dependency here?

cc @minrk

**Comment by michaelpacer** [comment]
https://github.com/jupyter/nbconvert/blob/master/nbconvert/preprocessors/csshtmlheader.py#L52
https://github.com/jupyter/nbconvert/blob/master/nbconvert/preprocessors/csshtmlheader.py#L56
https://github.com/jupyter/nbconvert/blob/master/nbconvert/preprocessors/csshtmlheader.py#L116

The frequency of internal imports here make me think they are purposeful. However, I still would have guessed that a `pygments.formatters` import could be moved to the top of the page (L52).

I see that this is using `nbconvert.resources` suggesting my guess that we dynamically use `nbconvert.resources` was on…however it's not clear to me how this is being used because right now it seems to be trying to extract a `style.min.css` from this resources directory, but there's nothing in that directory (at least not in the static code-base). Given that I cannot figure out how this piece is working I won't venture a guess as to whether this internal import is or is not necessary.

It is not obvious to me why the try loop around `from notebook import DEFAULT_STATIC_FILES_PATH` could not be imported at the top of the file. Is there a reason for its internal positioning?

**Comment by michaelpacer** [comment]
https://github.com/jupyter/nbconvert/blob/master/nbconvert/postprocessors/serve.py#L80
https://github.com/jupyter/nbconvert/blame/master/nbconvert/postprocessors/serve.py#L104

Both of these imports seem like they could be moved to the top?

The try loop for `from tornado import log; log.app_log = self.log` seems pretty self contained, however I can see that the try loop is also acting as an if statement for defining `self.log` which would be more rickety if you were to need to declare it up top. Is there another code pattern that would also accomplish this (e.g., something akin to the `if PY3` used elsewhere to ask about which python version is in use, but for tornado)? If not, I see why we should keep the import there.

The `sys` import seems like it can be moved to the top level easily. Is there a reason to keep it local to the `__main__` function?

cc @minrk × 2

**Comment by michaelpacer** [comment]
https://github.com/jupyter/nbconvert/blob/master/nbconvert/postprocessors/tests/test_serve.py#L19

So it looks like the `from ..serve import ServePostProcessor` is actually playing the role of being what is tested — is that accurate? If so, I see why it needs to appear internal to the function.

cc @minrk

**Comment by minrk** [comment]
I have credit for a lot more of these lines than I actually wrote, because I did the migration to the `nbconvert` package, which involved a lot of find/replace, especially in imports.

Regarding delayed imports as a whole: In general, delaying imports to when they are used has a few benefits, deriving from the fact that only what is used is imported. This generally has two goals:

1. optional dependencies, so that importing the top-level module does not trigger a failed import on a missing dependency that doesn't get used.
2. startup time - avoiding loading modules that don't get used, saving time during startup of the application. It also benefits startup time even when they are used, because the import doesn't happen until a later point, improving the responsiveness of early failure (e.g. missing arguments, etc.).

nbconvert has more of these than the rest of IPython/Jupyter because it has many diverse dependencies, only a small subset of which are likely used in any given use of nbconvert.

This should apply to most, if not all, of the cases in exporters, filters, pre/postprocessors, etc. There may be a few cases where what were optional dependencies that are no longer, in which case they serve little to no benefit, but also have no cost.

Some specific notes:

> https://github.com/jupyter/nbconvert/blame/master/nbconvert/tests/base.py#L127

I think this one has no reason at all, and can be moved, and this may be the case for many of the instances in tests.

> Is there a reason relative imports are bad for this?

When locating files in the package, absolute imports are often more convenient. It doesn't matter, though. Whatever the author chooses at the time is generally fine.

> The sys import seems like it can be moved to the top level easily. Is there a reason to keep it local to the `__main__` function?

It is common when imports are only used in the off-by-default `if-main` block for the imports only used there to be in the block.

> https://github.com/jupyter/nbconvert/blob/master/nbconvert/postprocessors/tests/test_serve.py#L19

note the try/except: Skip in this one. It's checking for the availability of the dependencies, and skipping the test if they are missing.

**Comment by michaelpacer** [comment]
@minrk Thank you for covering all this. I'm still going to move forward with the entire audit and then will loop back and try to analyse everything once all the cases have been gathered.

But my notes and intuitions will probably reflect that knowledge that you've imparted above. Grazie.

**Comment by michaelpacer** [comment]
https://github.com/jupyter/nbconvert/blob/master/nbconvert/filters/strings.py#L193

Looks to be an optional import so that `IPython` is not required to run `nbconvert`. I'm guessing this is also why ipython_genutils was moved into its own package (since there are strict dependencies on that throughout the codebase).

cc @minrk

**Comment by michaelpacer** [comment]
https://github.com/jupyter/nbconvert/blob/master/nbconvert/filters/highlight.py#L49
https://github.com/jupyter/nbconvert/blob/master/nbconvert/filters/highlight.py#L86
https://github.com/jupyter/nbconvert/blob/master/nbconvert/filters/highlight.py#L113
https://github.com/jupyter/nbconvert/blob/master/nbconvert/filters/highlight.py#L114
https://github.com/jupyter/nbconvert/blob/master/nbconvert/filters/highlight.py#L115
https://github.com/jupyter/nbconvert/blob/master/nbconvert/filters/highlight.py#L148
^ pygments imports

https://github.com/jupyter/nbconvert/blob/master/nbconvert/filters/highlight.py#L128
https://github.com/jupyter/nbconvert/blob/master/nbconvert/filters/highlight.py#L136
^ ipython imports

The only reason i see for not importing the pygments stuff at the top is if this has a slow loadtime. We already require pygments so it can't be avoiding the dependency. 

Also I just noticed the message of one of the commits was 
> never import pigments at module level in nbconvert
> 
> ensures things are always importable, and delays ImportErrors until they are actually relevant.

which I'm guessing means that there was a good reason for it (which would also apply to a number of earlier issues).  

But does including pygments at the module level stop things from always being importable? Why aren't import errors relevant at the module level but only the function level?

If it is a matter of loading time…I'm not sure how to test that to establish a comprehensive audit with reasons for doing everything in the audit.

What is the method that best trades off accuracy and coding time in order to test the load time of a module under some changes? I have a vague idea of how i'd approach this interactively, but I have to imagine there's a better practice than whatever I would hack together just based on the clunkiness of my intuition itself.

The IPython imports I imagine are dependencies that we are trying to avoid making into strict dependencies.

cc @minrk ×7
cc @takluyver

**Comment by takluyver** [comment]
Pygments does have a slow load time (because it uses pkg_resources, which annoyingly does slow things on import). But I think that pygments used to be an optional dependency before the Big Split, and that's why there are imports of it inside functions like this.

**Comment by michaelpacer** [comment]
https://github.com/jupyter/nbconvert/blob/master/nbconvert/exporters/templateexporter.py#L181
https://github.com/jupyter/nbconvert/blob/master/nbconvert/exporters/templateexporter.py#L298

It states explicitly that these imports are delayed so as to delay ImportErrors until runtime. However, now that Jinja is a hard dependency (whereas I get the impression that it wasn't before) shouldn't we not need to worry about import errors occurring for a properly provisioned system?

cc @minrk 
cc @takluyver

**Comment by michaelpacer** [comment]
https://github.com/jupyter/nbconvert/blob/master/nbconvert/exporters/tests/test_export.py#L95

So this looks like a pretty good candidate for moving to the top set of import statements. It's only being used to identify the path of the `nbconvert.tests` module via its `__file__` attribute. 

@minrk

**Comment by michaelpacer** [comment]
@takluyver What's a good workflow for testing the degree to which a earlier pygments load would slow down nbconvert? I'm not saying for the purposes of changing it, but because if I had wanted to figure that out myself I'd be at a loss as to a good way to do that, and I'm guessing there's a generally accepted practice regarding how.

**Comment by takluyver** [comment]
It shouldn't slow down nbconvert as a command line application, because nbconvert is almost certainly going to load it at some point. The difference would be to an application like the notebook which loads nbconvert but may not use it.

You can test the load time of pygments by doing:

```
time python -c "import pygments.styles"
```

That takes ~90ms on my laptop.

(I recommend doing it by starting a new Python interpreter because importing a module that's already been loaded takes a shortcut, so you can only measure it once per interpreter. And be careful testing anything inside IPython, because many modules will already be loaded.)

-----

For performance testing on Linux, I also use a command from [here](https://wiki.openoffice.org/wiki/Cold-start-simulator) to drop disk caches, forcing it to re-read everything from disk:

```
sync ; echo 3 | sudo tee /proc/sys/vm/drop_caches
```

This makes the test more like a 'cold start', when you've just turned the computer on. On machines with spinning hard drives, this makes a *massive* difference, and even with SSDs it makes things several times slower. There may be ways to do similar things on other platforms, but I don't know what they are.

**Comment by michaelpacer** [comment]
So I was thinking is there a way to script a solution where it jumps between two git branches one with the earlier load location and one with the later load location. 

Is there a way to do this within python or would I want to write it as a bash script to avoid the problems with cached libraries?

So would I want to be testing this in terms of launching a notebook (which loads nbconvert) rather than nbconvert as is? 

Also I don't fully follow how – if the command line nbconvert would load pygments almost surely –  we would avoid that when using it as a library? Is it because it only loads parts of nbconvert when they are invoked, meaning (for example) that pygments isn't loaded when you export notebook as a script from the notebook drop down menu?

**Comment by takluyver** [comment]
> So I was thinking is there a way to script a solution where it jumps between two git branches one with the earlier load location and one with the later load location.

Yes, but I'm unsure why you'd want to script that bit. I'd test something one way, switch manually, and test it the other way.

> So would I want to be testing this in terms of launching a notebook (which loads nbconvert) rather than nbconvert as is?

Probably not, because the web interface requires manual interaction, so you can't easily time its startup. You could work around that, but there's so many different things going on that timings will probably have a lot of random variation. This is why I was thinking of testing the pygments import in isolation.

> Also I don't fully follow how – if the command line nbconvert would load pygments almost surely – we would avoid that when using it as a library? Is it because it only loads parts of nbconvert when they are invoked, meaning (for example) that pygments isn't loaded when you export notebook as a script from the notebook drop down menu?

Exactly. If `pygments` is imported inside the function that uses it, then it won't be called unless something calls that function - i.e. converting a notebook to HTML or Latex. We often use the notebook server without doing those things, so we may prefer not to spend time loading pygments at startup. Or we may decide that startup performance isn't very important and we'd rather simplify the code a bit. But if pygments is the only thing we load that imports `pkg_resources`, it may be slower than other modules.

**Comment by minrk** [comment]
re: pkg_resources, you also have to be a bit careful about how you installed nbconvert (or whatever entrypoint you are invoking). A 'regular' install (pip or conda) won't invoke pkg_resources, but a `setup.py develop` or `pip install -e` dev-install will still invoke pkg_resources in the entrypoints, I think. Whoever first invokes pkg_resources will get the penalty, which may or may not be what you are measuring.

In general, I would leave all of the pygments imports where they are. The same would go for other large packages that are less likely to be used: IPython, jupyter_client, etc.

I think that only leaves the `jinja2` imports and a couple in the tests to be moved, the rest left alone.

**Comment by michaelpacer** [comment]
So one of the imports that seems strange still is the 

```python
        try:
            from tornado import log
            log.app_log = self.log
        except ImportError:
            # old tornado (<= 3), ignore
            pass
```

Here it seems that we're using the import statement as an implicit check as to whether the package is present and inlining it as if it were a conditional statement. We can split this into a ImportError at the top and a NameError inside the function if we want it (or set `log=None` at the top and then use `if log` below). 

Edit: Talked to @Carreau and he suggested since tornado 4.0 has been released since July 2014, we can just make that a requirement and get rid of the conditional logic. Also since 5.0 is a major version release, this is the right time to upgrade dependency version requirements.

**Comment by takluyver** [comment]
We already require tornado >= 4.0 for the notebook, so +1 to requiring it here too.
