### ISSUE TITLE
Printing html export loses code highlighting

### ISSUE THREAD

**Issue by petrpulc** [jupyter/nbconvert#459]
Well, in fact, all text is forced to be black on print by the css blindly taken from https://github.com/h5bp/html5-boilerplate/blob/master/src/css/main.css ...

As this is very inconvenient, I would like to propose a fix of the nbconvert/resources/style.min.css ... but it is copied from your CDN somewhere...

Therefore I attach the patch in hope that the CDN version will be fixed...

[patch.txt](https://github.com/jupyter/nbconvert/files/577793/patch.txt)

**Comment by takluyver** [comment]
Thanks! The CSS is taken from [jupyter/notebook](https://github.com/jupyter/notebook) if you want to make a PR over there. It may need some thought, though: if you're printing to black & white output, it's probably best to suppress the highlighting colours. Does CSS have a way to style things different for b/w printing?

**Comment by michaelpacer** [comment]
So from looking at the css header preprocessor (https://github.com/jupyter/nbconvert/blob/a5057f6/nbconvert/preprocessors/csshtmlheader.py#L55) specifically the `_generate_header()` function you can see that it's pulling in CSS from a few places. In addition to some hard coded stuff, it's grabbing any custom css you have and some things from pygments. You could inject a custom css file using that path and the csshtmlheader preprocessor.

It'll also grab code from https://github.com/jupyter/notebook/blob/master/notebook/static/custom/custom.css but that is, but for some comments, an empty file. The comments explain that it is to be overwritten by profile/static/custom/custom.css; which I imagine is another location that you could include some custom css, but that seems to be redundant with the mechanisms that nbconvert already has in place (and not to mention I'm having difficulty finding the documentation on exactly how that is supposed to work). 

Regardless, I cannot find any place that we are pulling from h5bp, so I wonder if you have a copy of that that is somehow being seen as an extra static path and then loaded as part of your html conversion steps. 

Because this doesn't seem to be related to core nbconvert issues, I'm going to close this issue. We can reopen if I prove to be wrong.
