### ISSUE TITLE
Incorrect conversion of equations with \[ \] delimiters

### ISSUE THREAD

**Issue by jfbercher** [jupyter/nbconvert#477]
Create a cell with
```
Equation
\[
y
\]
```
This equation displays correctly in the notebook, but converts to
```
    Equation {[} y {]}
```
in LaTeX (by `jupyter nbconvert --to latex FILE.ipynb`), and to
```
Equation
[
y
]
```
in html (by `jupyter nbconvert --to html FILE.ipynb`) and *sometimes* displays correctly, sometimes not. 
The notebook source is
```
   "source": [
    "Equation\n",
    "\\[ \n",
    "y \n",
    "\\]"
   ]
```
as it should.

Hence it seems that the delimiters are not recognized as math delimiters during conversion and thus treated as escaped strings. 
Is that reproducible elsewhere and what can I do? Thanks

**Comment by michaelpacer** [comment]
I don't know why for you it is displaying correctly in the notebook, I'm working on the master branch of the notebook (and i checked on 4.2.3 and 4.2.1) and it should display "Equation [ y ]"

There are some long standing issues with using backslashes in the notebook and in general because of the need to escape them.

My general suggestion is to use `$$ … $$` syntax even though it is advised against by others if you are going to be converting to LaTeX (since technically it's a TeX command and slightly messes with the spacing in LaTeX) because there are no issues that arise with escaping.

**Comment by jfbercher** [comment]
Hmm. 
After checking, it displays correctly in the notebook because I use the [jupyter_latex_envs](https://pypi.python.org/pypi/jupyter_latex_envs) notebook extension which takes care of extracting maths environments from markdown before markdown --> html (via marked) conversion. 
I will look if this can be used also when exporting.

**Comment by michaelpacer** [comment]
It looks like that package includes nbconvert exporters with entrypoints to point to them, so if you use `jupyter nbconvert --to latex_with_lenvs FILE.ipynb` or `jupyter nbconvert --to html_with_lenvs FILE.ipynb` does that solve your issue?

**Comment by jfbercher** [comment]
@michaelpacer I have updated  [jupyter_latex_envs](https://pypi.python.org/pypi/jupyter_latex_envs) to deal with the export of both latex maths structures, \\[ . \\] and \\(.\\) so it works for me now and it is fine. 

Anyway I think that it should be a good idea to have that supported in the notebook and nbconvert since LaTeX users tend to use that (and namely pandoc exports maths under these forms). I imagine that this has been discussed? 
A possible root of that is that the MATHSPLIT regex in mathjaxutils does not consider \\[ or \\( as valid math delimiters, then they are converted as markdown and finally not interpreted by mathjax (in addition the content equation is also converted "from markdown"). This is also the case in markdown_mistune where \\[ or \\( are not considered as valid math delimiters. Do you think/know if it would be of interest to propose some small updates for that?

**Comment by michaelpacer** [comment]
I'm 100% not sure why it was originally placed there is but what counts as a valid math delimiter in mathjaxutils are `\\( \\)` and `\\[ \\]`
([see here](https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/mathjaxutils.js#L15)) but my guess is that it's related to escaping the backslashes. 

@Carreau @takluyver @minrk is there another reason why we don't treat `\[ \]` and `\( \)`as delimiters in the notebook? It also causes issues in how we interpret markdown, where underscores in maths need to be escaped in some cases but not in others (which then makes for invalid LaTeX output in order to have a valid display in the notebook). That's why I'd always that recommended people use `$$ $$` and `$ $` (since it avoided some of these problems), but that (specifically `$$ $$`) is officially discouraged by the LaTeX community.

I'd brought this up a little over a year ago: https://github.com/jupyter/notebook/issues/759 (though I assumed we had to escape the backslash for it to work) and it was added to the 5.0 milestone, so that makes me think that there's support for fixing this in both notebook and nbconvert.

**Comment by michaelpacer** [comment]
Ok. So the MATHSPLIT regex is definitely missing some stuff, but almost all of that code could do with a review as a lot of it hasn't been touched for 3 years or more.

@jfbercher can you point me to the parts of jupyter_latex_envs that are solving this part of the problem? I can dive into the code, but that will take longer.

**Comment by jfbercher** [comment]
## Displaying \\[ \\] delimited equations in the notebook
For displaying eqs in the notebook, I do not really solve the MATHSPLIT regex but use a simple workaround. Actually, `latex_envs` patches the original Markdown renderer. Just before calling `mathjaxutils.remove_maths` (which invoked the regex above), I replace LaTeX \\[ \\] and \\( \\) delimiters by $$ $$ and $ $. Since these are interpreted correctly by mathjax, the display is fine, and this doesn't change the notebook itself. 

This is a workaround, but working; I think that a more direct  way to tackle would be to rework the regex and perhaps the lines below.

 [latex_envs.js, lines 127-134](https://github.com/jfbercher/jupyter_latex_envs/blob/master/src/latex_envs/static/latex_envs.js#L127-134)
```
  // interpret \[..\] and \(\) as LaTeX
            text = text.replace(/\\\[([\s\S]*?)\\\]/gm, function(w,m1){
                return "$$"+m1+"$$"})
            text = text.replace(/\\\(([\s\S]*?)\\\)/gm, function(w,m1){
                return "$"+m1+"$"})
            var math = null;
            if (text === "") { text = this.placeholder; }
            var text_and_math = mathjaxutils.remove_math(text);
```

## For converting to LaTeX and html
### LaTeX
It is assumed that the user has entered equations delimited by \\[ \\] and/or inline by \\( \\). It is also assumed that the actual conversion is done by pandoc. Noticing that pandoc converts $$.$$ in markdown to \\[. \\] in LaTeX, it is then enough to replace (again) \\[..\\] by $$..$$ and let pandoc do the work. 

This is implemented in a preprocessor, [latex_envs.py, lines around 92-122](https://github.com/jfbercher/jupyter_latex_envs/blob/master/src/latex_envs/latex_envs.py#L92-L122)
```
        def inline_math_strip_space(self,match):
        return "$"+match.group(1).replace(' ','')+"$"
```

conversion to LateX (preprocessor)
```
        if cell.cell_type == "markdown":
            data = cell.source
            data = re.sub(r'\\\[([\s\S]*?)\\\]', r'$$\1$$', data) #$$.$$ is converted into \[.\] #noqa
            data = re.sub(r'\\\(([\s\S]*?)\\\)', self.inline_math_strip_space, data) #$.$ converted into \(.\) #noqa
```

### HTML conversion
It is the same story for html conversion. The conversion is done using `markdown-mistune` where it seems that the delimiters \\[ and \\( are not considered, though it would not be difficult. The workaround is still again to replace by the $ forms, since finally the html will be interpreted by mathjax and the display correct. This is done by a preprocessor
[latex_envs.py, lines around 166-169](https://github.com/jfbercher/jupyter_latex_envs/blob/master/src/latex_envs/latex_envs.py#L166-L69)
HTML preprocessor
```
        if cell.cell_type == "markdown":
            cell.source = re.sub(r'\\\[([\s\S]*?)\\\]', r'$$\1$$', cell.source)
            cell.source = re.sub(r'\\\(([\s\S]*?)\\\)', r'$\1$', cell.source)
```

**Comment by jfbercher** [comment]
Just a note to explain that I posted the issue here because I had implemented some times ago a small code to display correctly the \\[ \\] delimited equations in the notebook, and then forgot it... 
Recently I realized that some conversions issues where linked to these equations and incriminated `nbconvert`, though the limitation is also present in the notebook itself.

**Comment by michaelpacer** [comment]
Thank you for being so thorough, I'll try to work through this.

I had had a quick look at what it was doing before and earlier today (when responding to you) and I had thought that there was a lot of conversion from the `\[ \]` formulation to `$$ $$` formulation…which confused me since I thought that was what you were trying to avoid. Knowing that you were working with the notebook/nbconvert's extant mechanisms + relying on pandoc in the end makes a lot of sense.

**Comment by jfbercher** [comment]
I pushed a PR to enable these maths delimiters in the notebook [notebook/#1935](https://github.com/jupyter/notebook/issues/1935) but this was not accepted for the reason described in the comments. This is a limitation for LaTeX users (limiting eg simple copy and paste from an existing documents) but we can live with it since working in the notebook is so nice (and these maths delimiters are supported in the `jupyter_latex_envs` nbextension). 
For the nbconvert side, it appears that there is finally no need to add support for these delimiters since they shoud not appear in the notebook. Therefore I close the issue. Thanks.

**Comment by michaelpacer** [comment]
Just as an aside, I believe that we're already using browser copying and pasting functionality explicitly in the notebook, so there may be a way to accomplish this particular use case. In particular, I can imagine that one possibility for copying and pasting from existing documents would be to try to catch the content of the text on paste and offer to automatically convert `\(` …`\)` and `\[` … `\]`  to `$` … `$` and `$$` … `$$`. I'm not entirely sure if this is possible or where it would be implemented, but I thought I'd mention it.

One thing additional feature that might be nice in `jupyter_latex_envs` is a way to have both the preferred delimiters while also being able to escape `[`,`]`,`(`, and `)` to have as literal characters. If you can develop a working, implemented standard for how that can be accomplished, I see that as having the best chance to sway CommonMark into adopting a solution that meets your goals (which means that Jupyter would inherit it as well).
