### ISSUE TITLE
Custom mime type

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/nbconvert#481]
When converting to html Would it be possible to convert datatypes in the form of `application/****+json`
to `script` tags if the same mime type containing the corresponding json?

For example, I guess

```json
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "11a0e82dc6cf47b3aa0cf241705fd85b"
      }
     },
     "metadata": {},
     "output_type": "display_data"
    }
```

would become

```html
<div class="output">
<div class="output_area">
    <div class="prompt"></div>
    <script type="application/vnd.jupyter.widget-view+json">
    {
       "model_id": "11a0e82dc6cf47b3aa0cf241705fd85b"
    }
    </script>
</div>
</div>
```

**Comment by SylvainCorlay** [comment]
So I guess

```json
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "11a0e82dc6cf47b3aa0cf241705fd85b"
      }
     },
     "metadata": {},
     "output_type": "display_data"
    }
```

would become

```html
<div class="output">
<div class="output_area">
    <div class="prompt"></div>
    <script type="application/vnd.jupyter.widget-view+json">
    {
       "model_id": "11a0e82dc6cf47b3aa0cf241705fd85b"
    }
    </script>
</div>
</div>
```

**Comment by SylvainCorlay** [comment]
^ ping @michaelpacer

**Comment by michaelpacer** [comment]
My intuition is that we would need to support that in the [display priority skeleton template](https://github.com/jupyter/nbconvert/blob/560a1fc/nbconvert/templates/skeleton/display_priority.tpl) and (possibly) the [filter_data_type filter](https://github.com/jupyter/nbconvert/blob/1c8a514901557335cf24b70fb427d461d32e6243/nbconvert/filters/datatypefilter.py) since that seems to be how we're sorting through the mimetypes in output right now.

The current approach is based on a bunch of manually encoded mimetypes which I believe is due to the static nature of the current Jinja2 based template architecture. My guess is that to support this we would need to be able to programmatically generate templates in memory (which is something that @carreau and @takluyver and I have talked about a bit). Doing that would allow a much more than just custom mimetypes (e.g., better foreign language support in PDF and LaTeX since we could inject the appropriate commands into the preamble). But it probably be one of the biggest overhauls to the current architecture that we've handled in nbconvert in a while. 

So right now I'm going to put it on a wishlist issue, and make a in memory templates GitHub project to organise these kinds of issues in one place.

Also to clarify, I'm pretty sure we can detect the mimetype name using regex (this would probably require a new filter of our own design), but it looks like blocks need to be named statically in templates. We might be able to get away with a "custom_json" block name, but then, we would need to treat all the custom_json blocks the same. Even then, we'd somehow need to pass the information down about the mimetype (which we might be able to do with scoped variables).

**Comment by SylvainCorlay** [comment]
Two fixed mime types that would enable inline widgets would be

`application/vnd.jupyter.widget-view+json``

and 

`application/vnd.jupyter.widget-state+json`.

If they were replaced as described above, that would already bring us pretty far.

**Comment by michaelpacer** [comment]
Ok, PR #482 is in the works, let me know if it works for you.

I'm going to follow the convention laid down with and add an element variable as well in [this commit](https://github.com/jupyter/nbconvert/commit/5b3f6ba022f59f1eb21fc60140cd1b0b9d2a3a06)

question: shouldn't there be a semicolon after the json object description? Maybe I'm off, but I have no way to test whether this is accomplishing what you wanted, I was just working off of the example you gave.

also, as it stands this will create a slightly different structure than what you had, but it seems still compatible with what you want. 

generated_unique_id would be actually generated by `uuid.uuid4()`
extra_class is actually a variable that could either be assigned "output_execute_result" if the output is included inside a execute_result block.

```html
<div class="output">
<div class="output_area">
    <div class="prompt"></div>
    <div id="generated_unique_id"></div>
    <div class="output_subarea output_widget_view extra_class">
        <script type="application/vnd.jupyter.widget-view+json">
        var element = $('#generated_unique_id');
        {
           "model_id": "11a0e82dc6cf47b3aa0cf241705fd85b"
        }
        </script>
    </div> 
</div>
</div>
```


I'm a little confused about whether they should be added to the list of datatypes defined in https://github.com/jupyter/nbconvert/blob/e4ddd08/nbconvert/utils/base.py since I don't see `application/javascript` included there which seems to be the closest datatype to those existing.  Just to check, @juhasch was the last to touch that line, Jürgen do you have any comments about the role of that line independent of the data display priority skeleton list?

**Comment by juhasch** [comment]
I only looked into the display priority and can't say much about additional datatypes.

**Comment by michaelpacer** [comment]
Since this is merged, I'm going to close for now, I imagine there may be other issues, but they should be considered separately.
