### ISSUE TITLE
Update notebook CSS version

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/nbconvert#496]
There is a variable in the setup.py file that determines which version of the notebook's CSS we are using for nbconvert. We released updated CSS in 4.3 of the notebook and we should update that link and make sure the CSS files are on the CDN. Not sure which versions of nbconvert this should go into. Maybe both 4.3 and 5?

**Comment by michaelpacer** [comment]
My instinct is to just do a patch release on 5.x along with #491 rather than backporting to 4.3. 

But that's mostly because I hadn't planned on releasing anything more on the 4.x branch. I only created it for the rapid release of the live widget outputs when master was already on 5.0.0dev. And there are relatively few reasons why people would be unable to move to the 5.x line of releases, #490 was the only issue we've received related to it so far & dependencies didn't change all that much.

**Comment by takluyver** [comment]
I think it's fine to just do it on 5.x. Once we have released `(x+1).0` of a package, we very rarely make any more releases from series `x`. We might do it for a critical security fix, but not for table styling.
