### ISSUE TITLE
proper way to enable `matplotlib inline`

### ISSUE THREAD

**Issue by arsenovic** [jupyter/nbconvert#523]
i am using nbconvert through nbsphinx and readthedocs. what is the recommended way to enable matplotlib inline for all my notebooks?

**Comment by takluyver** [comment]
Generally, we recommend putting `%matplotlib inline` in all notebooks, so that they run the same way for anyone, without needing to be started in some special way. By analogy, you probably wouldn't look for a way to have numpy pre-imported in all notebooks, because then they would break for anyone who tried to run them normally.

If it's really necessary to do something before processing all notebooks, you can put it in an IPython startup file.

**Comment by arsenovic** [comment]
ok, thanks for the advice. do you have any experience with using an ipython startup file with readthedocs?

**Comment by takluyver** [comment]
Hmm, doing anything on RTD tends to be a bit fiddly - you have to fiddle with files like `conf.py` to get code to run before your build. @mgeier (author of nbsphinx) might have some suggestions.

**Comment by mgeier** [comment]
`nbsphinx` doesn't use the IPython startup file.
I don't think there is no other way than using `%matplotlib inline` in each notebook, which is the most reasonable thing to do anyway, IMHO.
If you don't want to see the command in the output HTML/LaTeX, you can hide the code cell. But I think in general it's easier for your audience to follow what's going on, if you don't hide stuff.

**Comment by t-makaro** [comment]
Closing as answered. Please comment asking to re-open if needed.
