### ISSUE TITLE
Convert to pdf misses Markdown without Extra Lines

### ISSUE THREAD

**Issue by WillClaudeHolmes** [jupyter/nbconvert#538]
There are several instances in which converting to pdf will not catch markdown unless there is an extra line before the markdown element.  For instance, a list

    -  List item 1
    -  List Item 2
    -  List Item 3

will convert to     "-  List item 1 -  List Item 2 -  List Item 3" and all be in one paragraph.  If instead, there are extra lines in the list, it will convert correctly.  That is

    -  List item 1

    -  List Item 2

    -  List Item 3

converts to
-  List item 1
-  List Item 2
-  List Item 3.

I have also experienced this with heading tags.  For instance

    blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah
    ## Heading 2

Converts to
"    blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah ## Heading 2"

The ## as heading markers are missed and are instead included in the output.

**Comment by michaelpacer** [comment]
Because they are block elements, I believe that both headings and lists need to have the first line of the block prefixed by a blank line. It doesn't exactly say this in [md on headers], but it does describe this as necessary for other blocks. It may be enough to have a line end with two spaces and a new-line, but I don't think that will work under all markdown parsers.

However, the list items shouldn't need blank lines before each instance, unless you want them to be wrapped in paragraph tags (see [md on lists][]), can you give an example notebook that won't convert properly if you don't have new lines between your list items?

If the interactive notebook does not adhere to this, that's a problem with the notebook's javascript markdown renderer in that it is being more permissive than markdown allows.

Unless I misunderstand what you're saying this isn't really a "bug" so much as "what it means to write in a stricter version of markdown". So I'm closing, but will reopen if there was a misunderstanding.

[md on headers]: https://daringfireball.net/projects/markdown/syntax#headers
[md on lists]: https://daringfireball.net/projects/markdown/syntax#list

**Comment by WillClaudeHolmes** [comment]
> However, the list items shouldn't need blank lines before each instance, unless you want them to be wrapped in paragraph tags (see md on lists), can you give an example notebook that won't convert properly if you don't have new lines between your list items?

An example is [this notebook](https://github.com/WillClaudeHolmes/Jupyter_Examples/blob/master/Problem_6_29.ipynb) which when run through `jupyter nbconvert --to pdf .\Problem_6_29.ipynb` produced this [pdf document](https://github.com/WillClaudeHolmes/Jupyter_Examples/blob/master/Problem_6_29.pdf).  The conversion to HTML with `jupyter nbconvert --to HTML` [works fine](https://github.com/WillClaudeHolmes/Jupyter_Examples/blob/master/Problem_6_29.html).

The relevant section is the markdown at the very beginning of the notebook which is
    1. Plot the data as engineering stress versus engineering strain.
    1. Compute the modulus of elasticity.
    1. Determine the yield strength using a strain offset of 0.002.
    1. Determine the ultimate tensile strength of this allow.
    1. Determine the ductility in percent elongation.
    1. Compute the modulus of resilience.

This is converted to 

>  1. Plot the data as engineering stress versus engineering strain. 1. Compute the modulus of elasticity. 1. Determine the yield strength using a strain offset of 0.002. 1. Determine the ultimate tensile strength of this allow. 1. Determine the ductility in percent elongation. 1. Compute the modulus of resilience.

**Comment by michaelpacer** [comment]
What happens when you put a blank line after the heading but before the
first instance of the list?

**Comment by WillClaudeHolmes** [comment]
@michaelpacer , OK, that worked correctly!!! Thanks so much for the help!
