### ISSUE TITLE
nbconvert doesn't depend on jupyter_client

### ISSUE THREAD

**Issue by amueller** [jupyter/nbconvert#553]
I'm running nbconvert on travis ci, and I noticed that nbconvert doesn't depend on ``jupyter_client``. But it seems it's needed to do ``--execute``. Is that intended?
If this is a soft dependency on purpose, maybe there should be a nicer error message, saying that you can use ``nbconvert`` but not ``execute`` without ``jupyter_client`` (if that is true).

**Comment by takluyver** [comment]
There's an extra so you can do `pip install nbconvert[execute]`.

I'm always wary of catching ImportErrors to give 'nicer' errors messages, because we've had cases before where that's caught an error from further down the stack (i.e. not the the thing we directly imported, but something imported by that), and made it harder to work out what was really going wrong.

**Comment by amueller** [comment]
fair point.
