### ISSUE TITLE
Execution of empty code cell produces duplicate `execution_count`

### ISSUE THREAD

**Issue by wstomv** [jupyter/nbconvert#657]
When an empty code cell is executed in the Jupyter Notebook Editor, the `execution_count` remains empty (`null`): `In[ ]`.

However, with `jupyter nbconvert --execute`, an empty code cell will receive a non-`null` execution count; in fact, it will get the same value as the execution count of the next non-empty code cell. This way, execution counts are not unique, which can be problematic (or at least confusing) when inspecting output history.

It is also an unfortunate discrepancy in the behaviors of these two execution mechanisms.

**Comment by mpacer** [comment]
So I just made a little progress on this. 

I don't think this is an nbconvert problem so much as it is a `jupyter_client` problem, since the content that we're getting back from the Kernel Manager's client message includes an execution count that is improperly incremented.

**Comment by mpacer** [comment]
Looking into it further I don't think it's a jupyter_client bug, because this is just passing through the message it may be an ipython kernel bug instead.

Some more context:

the message we get back from the kernel client is defined here:

https://github.com/jupyter/nbconvert/blob/0a262a3a00a1680c0b30c95b0b9837ed4f8ff063/nbconvert/preprocessors/execute.py#L359

and that message already has an incremented execution_count by the time we're receiving it. 

My guess is based on this example: https://github.com/jupyter/jupyter_client/blob/master/docs/wrapperkernels.rst#example

that there is some bug in the `do_execute` method's handling of execution count.

My guess is it's related to this:
https://github.com/ipython/ipykernel/blob/71c44fe80e79126de4f27e6713fda1d274132d77/ipykernel/ipkernel.py#L234-L235

```python
        # Return the execution counter so clients can display prompts
        reply_content['execution_count'] = shell.execution_count - 1
```

where something is happening with regards to shell.execution_count elsewhere that should be monitored more closely. 

@Carreau @takluyver @minrk how is this generally handled on the front end? Why isn't this a problem for the notebook?

**Comment by minrk** [comment]
The notebook frontend skips execution of empty cells. We could do the same in nbconvert.

**Comment by takluyver** [comment]
The system as a whole has always skipped over empty cells - they don't get executed. But I think we've never really defined whether that's the responsibility of the frontend code, `jupyter_client`, or the kernel. Evidently we've been relying on the frontend doing it. Probably the simplest solution is to do the same check in nbconvert.
