### ISSUE TITLE
Feature request: custom image file names

### ISSUE THREAD

**Issue by mhinsch** [jupyter/nbconvert#671]
By default nbconvert names generated image files using a fixed prefix and the cell number. While this is simple and nicely general it doesn't work well in scenarios where you want to re-use the generated images as part of a different workflow. As an example: I am working on a LaTeX document that includes figures generated from a jupyter notebook. No problem as long as the notebook doesn't change, but as soon as I insert cells at the beginning of the notebook all image file names change and have to be adapted manually in the LaTeX file.

I've had a long look through the documentation but I haven't been able to find a way to change that behaviour.

My suggestion: optionally let image file names be generated either from a heading preceding the cell containing the image or from a meta tag in the image cell itself. I've changed my local copy of nbconvert to use a tag "name" in place of the cell number if present (2 lines of code), but a proper implementation should probably make that optional and easily configurable.

**Comment by mpacer** [comment]
You can display more than one image per cell, so we can't really handle this at the cell level. It needs to be done at the output level.

How are you creating/displaying your images?

If you display the image using the IPython `display` function, you can assign metadata to the output itself (and even specific mimetypes), rather than to the cell. Then, we could look for a key in the output-level metadata (probably `filename`) and when we write out the file it would save to that file. 

One open question: 
@Carreau & @takluyver, if you had multiple files with the same manually assigned metadata name, would you overwrite the previous filename or automatically append a suffix? I'm leaning toward overwriting in order to make it explicit that if you're using this feature that your literal string will always be followed, but I'm open to being swayed in the other direction.

**Comment by mhinsch** [comment]
I'm not familiar enough with the code to comment on cell vs. output level (I am not even sure what that means). However, multiple images per cell are not a problem for the way I implemented it (which is still a hack, but for other reasons).

In preprocessors/extractoutput.py the output file name is pasted together from some metadata. The only change I made is to replace cell index with the content of the tag "name" if it exists. Different images within a cell are distinguished by index within cell. That still works independent of whether cell index itself is used or a name instead.
