### ISSUE TITLE
nbconvert failed: Inkscape svg to pdf conversion failed

### ISSUE THREAD

**Issue by JulieLen** [jupyter/nbconvert#769]
When I want to save my notebook as a PDF or Tex doc, I get this error message. 
I have downloaded the Inkscape app on Mac, and the Inkscape extension, but it did not changed much. 

I guess that somehow I need to tell Julia to take that "package" into account, but I don't know how. 
Could someone provide guidance ? 

Thanks !

**Comment by t-makaro** [comment]
This may be fixed by #985.

**Comment by t-makaro** [comment]
Closing issue as stale. If you'd like more information on similar issues see [my comment here](https://github.com/jupyter/nbconvert/issues/302#issuecomment-517487411). If your issue is not fixed and does not fit into one of the other issues mentioned my [comment](https://github.com/jupyter/nbconvert/issues/302#issuecomment-517487411), the please comment asking to re-open with any additional information.

**Comment by AshtonSBradley** [comment]
this is not fixed.

**Comment by MSeal** [comment]
> this is not fixed.

@AshtonSBradley  Need some more details on this one for setup, steps taken, versions of packages used. Haven't had many reports of this issue in the year since this was released.

**Comment by AshtonSBradley** [comment]
sorry, that was not a very helpful comment of mine. I must admit I have given up trying to do any of this now, I just export to html and print the pdf. Does mean I can't get latex out of it anymore though. 

Setup is MacOS 10.14.16, jupyterlab kernel is julia 1.4. 

Error message is (for pdf and latex export):
```nbconvert failed: Inkscape svg to pdf conversion failed```

Not sure how to track down relevant packages that jupyter knows about.
```
higgs:~ abradley$ which inkscape
/usr/local/bin/inkscape
```

**Comment by MSeal** [comment]
> Does jupyter use python 2 by default or something?

No, you might need to check where you're jupyter command is stored and see how it's launching python ... maybe it's installed from your system python 2 and ignoring your local environment? (I don't have an OSX machine to inspect this for you). Normally [these instructions](https://medium.com/@eleroy/jupyter-notebook-in-a-virtual-environment-virtualenv-8f3c3448247) do the trick (with `jupyter lab` instead of `jupyter notebook` for your case)

In the end I think you'd need to figure out what environment your jupyter lab is using and make sure it has nbconvert 5.6.1+ and is in python 3.5+.
