### ISSUE TITLE
Question: Is execution timeout based on wall clock or CPU time spent?

### ISSUE THREAD

**Issue by wstomv** [jupyter/nbconvert#776]
I have the impression that the timeout limit on cell execution is based on wall clock time rather than actual CPU time. Reason: it seems to use socket timeout in ZMQ (also see #256). Is this correct?

This seems to become problematic on our server, where we execute multiple (student) notebooks in parallel, and thus the timeout behavior becomes dependent on load, which obviously is undesirable.

In the future, I would recommend that kernels take a timeout value as input and enforce it when executing code; it should not be the duty of a kernel's client.

**Comment by takluyver** [comment]
Yes, it is based on wall clock time. I don't think doing it based on CPU time would be intuitive or even particularly useful - code can easily get stuck waiting for data from the network, or doing disk access, or communicating with other processes. In any of those cases, it would be using little CPU time, so it would appear that nbconvert was ignoring the timeout you had set.

This timeout is intended for "it should never take this long, something's gone wrong, abort it" rather than "the algorithm must complete in X seconds". If you want to check the latter, I'd set a significantly longer timeout (like 2X or 4X), record how long it took to complete, and then rerun any that took longer than X the first time.

**Comment by t-makaro** [comment]
Closing as answered.
