### ISSUE TITLE
Mathjax redraw in slides

### ISSUE THREAD

**Issue by akhmerov** [jupyter/nbconvert#79]
I have observed that slides generated by nbconvert from current master trigger mathjax redraws on every navigation event:

See
http://nbviewer.ipython.org/format/slides/url/antonakhmerov.org/misc/slides_mathjax_render.ipynb (nbviewer seems to have the same issue)

In case nbviewer code is modified, here's the generated html:
http://antonakhmerov.org/misc/slides_mathjax_render.slides.html

The bug manifests in blinking of `$\LaTeX$` when the next fragment is shown.

Resolving #67 could solve also this issue.

**Comment by damianavila** [comment]
This is because in nbviewer the mathjax redraw is associated to the `slidechanged` and `fragmentchange` events. Preoviously, only the `slidechanged` event triggered the redraw...

I think we probably have to go back and only triggers the redraw with the slidechange as the reveal.js math plugin does...

**Comment by takluyver** [comment]
Milestoned for 4.1 because it sounds simple and hopefully the fix can get in quickly, but we can bump it if necessary.

**Comment by takluyver** [comment]
@damianavila can you look into this? I'd like to be able to release 4.1 today or tomorrow.

**Comment by damianavila** [comment]
I will look into this at the evening if that works for you...

**Comment by takluyver** [comment]
OK, thanks

**Comment by damianavila** [comment]
I just submitted a fix @takluyver :wink:
