### ISSUE TITLE
Add support for pandoc >=2

### ISSUE THREAD

**Issue by ivanov** [jupyter/nbconvert#815]
With #814, we stopped the bleeding (or at least mitigated) the issues that come up for folks who end up using the more recent versions of pandoc. We should work through those issues and make pandoc 2 work.

**Comment by mpacer** [comment]
I think we're likely to have to _not_ support pandoc 1.19 because of the way they changed the rst exporter (or have support for either solution in the test…in which case we don't have deterministic behaviour).

I spent some time trying to track what it was that actually changed in the rst writer and I ended up a little stumped so we might have to throw some spaghetti at the wall if we want to try to change our internal syntax to accommodate their new converter. Have you had any luck?

**Comment by ivanov** [comment]
I haven't tried yet, but the test suite didn't pass with pandoc 2.2.1 - but it passes with 1.19.
