### ISSUE TITLE
NbConvertApp command line options not documented

### ISSUE THREAD

**Issue by rlabbe** [jupyter/nbconvert#837]
Viewing nbconvertapp.py I see command line options such as  inplace, clear-output, etc. Looking at the documentation for this app, usage.rst, I do not see any reference to these. A search on readthedocs reveal the changelog mentions them, but no one is going to go to a change log to understand what a command line will do.

I'm happy to try to edit usage.rst to fully document the command line options, but not sure on the workflow you are using. Should I just dive in and then issue a pull request?

**Comment by takluyver** [comment]
I don't think we explicitly try to document all the options in `usage.rst` - it's an overview rather than a comprehensive reference document.

You can see all the short command line options by running `jupyter nbconvert --help`, and all the config options that can be set at the command line with `--help-all`. The [config options doc](http://nbconvert.readthedocs.io/en/latest/config_options.html) also lists all these, though it doesn't show the shorter command line flags yet - that's waiting on a new release of traitlets, so we can use https://github.com/ipython/traitlets/pull/458.

**Comment by takluyver** [comment]
OK, PR welcome.

**Comment by t-makaro** [comment]
Closing as solved by #839 and #1048.
