### ISSUE TITLE
NBConvert Wrong Output Filename

### ISSUE THREAD

**Issue by Queuecumber** [jupyter/nbconvert#912]
I download my notebooks from Google Colab and for whatever strange reason, google doesn't use any file extension for these notebooks (they are otherwise completely normal jupyter notebooks). 

When the filenames given to nbconvert don't have an extension, nbconvert seems to eat the last letter of the filename. For example I have a notebook called "DCT". Calling 
```
jupyter nbconvert --to html ./*
```
on the folder with my notebooks results in "DC.html". When I rename the notebook to  "DCT.ipynb" then repeat the command, the result is "DCT.html" (e.g. correct). This also effects the HTML title element.

My guess is that this is a simple matter of assuming the file name ends in a '.' and deleting it without checking.

**Comment by t-makaro** [comment]
I believe the culprit is [this line](https://github.com/jupyter/nbconvert/blob/bf1850af16750a01ed6ca3293db839dc80db2b31/nbconvert/exporters/exporter.py#L171). ```rfind``` return -1 if no ```.``` is found which then cuts off the last character. This should be replaced with ```os.path.splitext```. I can submit a PR later unless someone else wants to take it.

**Comment by t-makaro** [comment]
Fixed by #1075
