### ISSUE TITLE
Duplicate Entries in Download as Menu

### ISSUE THREAD

**Issue by hansen-m** [jupyter/nbconvert#938]
After updating to the latest version of nbconvert I'm seeing duplicate entries for the exporters in the Download as menu. Any way I can remove or manage these? I'm running JupyterHub via Anaconda 3. 

<img width="339" alt="screen shot 2019-01-03 at 13 45 11" src="https://user-images.githubusercontent.com/1102305/50655552-8e48f800-0f5e-11e9-96f4-8238793baaa3.png">

**Comment by justmarkham** [comment]
I experienced the same behavior when I upgraded from nbconvert 5.3.1 to 5.4 (and that is the only thing I changed in my environment).

**Comment by t-makaro** [comment]
Dev note: Jupyter notebook added support for custom exporters in the menu [here](https://github.com/jupyter/nbconvert/pull/759). This added a ```export _from_notebook``` to allow custom exporters to be added to the menu. #759 Documented that change in nbconvert, and #864 added ```export_from_notebook``` to the built-in exporters (which then resulted in the built-in exporters being duplicated in the menu). I believe. This could be fixed, by reverting #864, or on the notebooks side.

**Comment by MSeal** [comment]
Hmm @t-makaro is right about the cause, I'm not sure what the intended pattern for UIs is supposed to be here. @mpacer @SylvainCorlay do either of you know those expectations better / can suggest the best change to make here?

**Comment by mpacer** [comment]
So this seems to be an issue on the notebook side rather than on nbconvert's side. Notebook has hardcoded values back in the days when nbconvert didn't make these as easily visible.


The template that has the hardcoding is here:

https://github.com/jupyter/notebook/blob/eea37a6b2110e0b8a5491f17e241fa3c8aecb5f7/notebook/templates/notebook.html#L113-L126

The logic for getting exporters lives in `get_custom_frontend_exporters` here: 

https://github.com/jupyter/notebook/blob/b8b66332e2023e83d2ee04f83d8814f567e01a4e/notebook/notebook/handlers.py#L18-L28

The jinja rendering that populates that template with the exporter names and display names is in the same file as the `get_custom_frontend_exporters` definition: 

https://github.com/jupyter/notebook/blob/b8b66332e2023e83d2ee04f83d8814f567e01a4e/notebook/notebook/handlers.py#L59

**Comment by mpacer** [comment]
Note this doesn't really solve the problem for 3rd party registered exporters; if they inherit from the existing nbconvert exporters, they will have the same `export_from_notebook` value and so it will produce additional duplicates, even if we get rid of the hard-coded redundant parts in notebook itself.

See https://github.com/jfbercher/jupyter_latex_envs/pull/44 as an example of how that can be fixed

**Comment by t-makaro** [comment]
This is a bit of a [hack](https://stackoverflow.com/questions/38275148/python-subclass-that-doesnt-inherit-attributes) (define ```__getattribute__``` in the base exporter), but we could force ```export_from_notebook```, not to be inherited by a subclass. That way by default subclassed exporters will not appear in the list without defining it themselves.

**Comment by t-makaro** [comment]
Or, on the notebook side the ```get_custom_frontend_exporters``` could check if ```export_from_notebook``` is the same as the one defined by the superclass, and then ignore it.
