### ISSUE TITLE
Pandoc 2.6 supports ipynb input/output

### ISSUE THREAD

**Issue by s1291** [jupyter/nbconvert#950]
According to pandoc 2.6 [changelog](https://pandoc.org/changelog.txt):
```
pandoc (2.6) PROVISIONAL

  * Support ipynb (Jupyter notebook) as input and output format.

    + Add `ipynb` as input and output format (extension `.ipynb`).
    + Added Text.Pandoc.Readers.Ipynb [API change].
    + Added Text.Pandoc.Writers.Ipynb [API change].
```

How does this affect nbconvert project?

**Comment by MSeal** [comment]
Late response, but I'm not sure this will affect nbconvert for sometime given we need to support old formats. From looking at the additions it appears exporting to particular formats might be able to simplify in the future by running the execute process and returning the results directly to pandoc. This could reduce some code burden in nbconvert, especially around latex. But it will depend on how many edge cases of underlying conversion tools are fixed in the wrapping library for how much this will be applicable to removing code in nbconvert. Still it's a neat improvement.
